### ISSUE TITLE
Request: Example/Tutorial on Integration with Isotope (layout/filtering/sorting)

### ISSUE THREAD

**Issue by igregson** [webcreate/infinite-ajax-scroll#142]
A quick feature request for an example or tutorial on integrating Infinite Ajax Scroll with Isotope. 

I've been trying to cobble together Paul Irish's infinite scroll plugin with Isotope for over a day now, which eventually lead me here. Was hoping for a near "plug and play" experience (ready to purchase commercial license and all) but so far even basic implementation isn't working (see issue #141). 

I'd love for a tutorial on integrating IAS with Isotope for layout, filtering, and sorting of _all_ data to be paged. On the site, a [Masonry example](http://infiniteajaxscroll.com/examples/masonry.html) is given, but not one for Isotope.

**Comment by monecchi** [comment]
+1 for an extension to support isotope and masonry alike layouts!!

**Comment by 10SexyApples** [comment]
+1 ... dealing with this now and may have to let go of infinite scroll unfortunately because I haven't been able to sort it out~
