### ISSUE TITLE
infinite ajax scroll + masonry + imagesloaded

### ISSUE THREAD

**Issue by aydcery** [webcreate/infinite-ajax-scroll#158]
this code is working fine , but sometimes leaving a gap , like this 

![issue](http://s30.postimg.org/xgkqzhogx/serious_pb_on_script.jpg)

and this is my code ;

    var container = document.querySelector('#container');
    var msnry;
    // initialize Masonry after all images have loaded
    imagesLoaded( container, function() {
    msnry = new Masonry( container, {
		itemSelector : '.box',
		isFitWidth: true,
		columnWidth: 236,
		gutter: 14
    });
	$('#loading').hide();
    });

    var ias = $.ias({
      container: "#container",
      item: ".box",
      pagination: ".page-links-list",
      next: ".page-next",
      delay: 0,
	  negativeMargin: 200
    });

    ias.on('render', function(items) {
      $(items).css({ opacity: 0 });
    });
	
    ias.on('rendered', function(items) {
	imagesLoaded( container, function() {
	msnry.appended(items);
	});
	});
	
	ias.extension(new IASSpinnerExtension());

Thanks in advance.

**Comment by fieg** [comment]
I think the gaps are caused because the images don't have a fixed height and are sometimes loaded after IAS. Therefor some offsets are calculated incorrect. Can someone verify this by trying to set fixed heights?

**Comment by fieg** [comment]
Closing due to no response.
