### ISSUE TITLE
infinitescroll keeps loading same content!

### ISSUE THREAD

**Issue by theprestigesvk** [webcreate/infinite-ajax-scroll#168]
Guys i need help with this. When i try on a single page the script works great. But when i implement it into my website, i see my first page content, but when i scroll it keeps loading the same page over. 

I tried to look at console log: 

Welcome at page 2, the original url of this page would be: http://localhost/katalinpresa/photography/?p=2
photography:162 
Welcome at page 3, the original url of this page would be: http://localhost/katalinpresa/photography/?p=2
photography:162 
Welcome at page 4, the original url of this page would be: http://localhost/katalinpresa/photography/?p=2

looks like the page is not changing. 

can anyone help ?

**Comment by fieg** [comment]
I'm closing this issue because this is a server side thing. I can't help with that.

**Comment by Parthvora** [comment]
I'm getting similar kind of issue. 
The "FIRST" infinite scroll AJAX call fires for more than one time like:
user-following?page=1
user-following?page=1
user-following?page=1

and I guess thats why I'm getting same records twice on same page.

Selectors are also correct.

AJAX calls after first call fires one time only. Thats is correct.

Please please please help me.
