### ISSUE TITLE
Have any Example for autoload previous page ?

### ISSUE THREAD

**Issue by memory-d** [webcreate/infinite-ajax-scroll#173]
I tried with so many way it doesn't work.

PS. When we scroll to the next page, How can we change Page title to be Page 2 ?

**Comment by seanbuscay** [comment]
+1 On this.  Is there a good event to use to trigger a change in the title? 

http://infiniteajaxscroll.com/docs/events.html

**Comment by fieg** [comment]
Duplicate of #179. I will pick it up from there.
