### ISSUE TITLE
How can I trigger load next page when user Scroll down 80% of page?

### ISSUE THREAD

**Issue by memory-d** [webcreate/infinite-ajax-scroll#174]
Because right now the function trigger load next page when user scroll to end of the page.
CAN ANYONE SHOW ME SOME APPROACH ?
Please suggest to me.

**Comment by fieg** [comment]
Please don't yell.

**Comment by fflewddur** [comment]
I think the negativeMargin option (http://infiniteajaxscroll.com/docs/options.html) does what you're looking for.

**Comment by memory-d** [comment]
@fflewddur Ohhhh Thank you so much.
