### ISSUE TITLE
Remaining previous pages after click back button.

### ISSUE THREAD

**Issue by ngoncom** [webcreate/infinite-ajax-scroll#179]
Hi,

See your example at: http://infiniteajaxscroll.com/examples/history.html, when I am at "page 4" and click item "Item 4.2", after that I click back button, I am back to "page 4" and have to click many times to back to "page 1".

Are there any ways to remaining 4 page loaded when click back button?

Thank!

**Comment by fieg** [comment]
This is hard to solve technically. Version 1.x of this plugin used a method that continuously loaded the previous pages up till the page where you left of, but it was very user unfriendly so removed from v2.x.

So to summarise: I don't see a way to solve this in a nice and user-friendly way.
