### ISSUE TITLE
Retain back button history

### ISSUE THREAD

**Issue by m9dfukc** [webcreate/infinite-ajax-scroll#181]
When using the history extension it would be nice to have an option to retain the back button history ... so clicking browser back button resolves to the previous loaded page.

**Comment by fieg** [comment]
It does exactly that already. But perhaps I'm misunderstanding you?

**Comment by m9dfukc** [comment]
At least not for the [history example](http://infiniteajaxscroll.com/examples/history/page4.html). When scrolling down to *page 4* and hit the browser back button you don't land on *page 3* but where you came from. Or did I miss something and this is already possible via a config flag?

**Comment by fieg** [comment]
It works in my browser (Chrome), what browser are you using?

**Comment by m9dfukc** [comment]
Using OsX Yosemite ... doesn't work in Chrome 41.x, doesn't work in Safari 8.x and doesn't work in Firefox 33.x.

So either I'm missing something or the history example is broken.

**Comment by m9dfukc** [comment]
To make it clear ... I search for the functionality to land on page 3 (after scrolling to page 4) when hitting the back button.

**Comment by fieg** [comment]
Oh, I understand now. You mean without clicking on an item. In that case I don't see how that would add value to the usability of infinite scroll, but that's my opinion. Perhaps you have some very good arguments why we should support this feature, which I would love to hear.

**Comment by m9dfukc** [comment]
It depends ... for using infinite scroll on an "posts archive" page it doesn't add any extra value imho. But I wanna replicate this effect here on the bloomberg.com [website](http://www.bloomberg.com/news/articles/2015-03-05/we-tried-to-re-create-jpmorgan-s-top-mutual-fund-returns-and-just-gave-up) (scroll to bottom until next article loads). Would you count that as an good argument ;?

**Comment by fieg** [comment]
When I scroll on that page I can't go back in the browser (Chrome). Nothing is added to the history...

**Comment by m9dfukc** [comment]
Hmm, you'r right ... somehow I had the impression that this pushes the state to the history. Anyway ... I'll just fork your plugin and add the option myself ;)

**Comment by fieg** [comment]
In theory you would only have to copy to HistoryExtension and change this line: https://github.com/webcreate/infinite-ajax-scroll/blob/master/src/extension/history.js#L34 from replaceState to something like addState (or whatever the history API uses for that). And then load your own extension.

Then there would be no need to fork the projects and can easily update to future versions without conflict.

**Comment by m9dfukc** [comment]
Jep, I know ... I already did that. By the way, it's history.pushState() not .addState() ;) 

Thanks!

**Comment by fieg** [comment]
:+1:
