### ISSUE TITLE
Toolbar number of items needs updating on success - 1-12 of 86 

### ISSUE THREAD

**Issue by jasonalvis** [webcreate/infinite-ajax-scroll#182]
Hello,

Great module, nicely built. Only issue I have come across so far is as you infinite scroll through the pages the toolbar text telling the user how many products they are viewing remains the same and needs to update.

Do you have a method to achieve this, I presume I could use the loaded event and count the number of items in the page and update the html in the toolbar? Has anyone already done this?

Thanks

**Comment by jasonalvis** [comment]
Found a quick solution:

Within init.phtml amend the on loaded function to the following:

```javascript
window.ias.on('loaded', function(data, items){
    var items      = $(items),
        products   = items.children(),
        element    = $(".js-ias-items"),
        currentNum = parseInt(element.text());

    element.text( currentNum + products.length );

    SgyIAS._log({eventName: 'loaded', data: data, items: items});
});
```
Within your toolbar template catalog/product/list/toolbar.phtml find the amount section and wrap the number around a span tag

```
<p class="amount">
<?php if($this->getLastPageNum() > 1): ?>
    <?php echo $this->__('Showing %s to <span class="js-ias-items">%s</span> of %s Items', $this->getFirstNum(), $this->getLastNum(), $this->getTotalNum()) ?>
<?php else: ?>
    <?php echo $this->__('%s Items Found', $this->getTotalNum()) ?>
<?php endif; ?>
</p>
```

**Comment by fieg** [comment]
Great to see you found a solution yourself. I think it is a very solid approach.
