### ISSUE TITLE
Preloading content

### ISSUE THREAD

**Issue by withoutmessage** [webcreate/infinite-ajax-scroll#187]
Thanks for this awesome plugin.
I am having trouble pre-loading content with the usual techniques (it works synchronously with the first set of elements using 'rendered' event when you first land, but not with the new content appended to the body). I am trying to show a rather large set of images I would like to load asynchronously, when each of them is actually fully loaded. I was wondering whether there is a conflict with the plugin or either a way to accomplish that behavior. 
Best,
Marc

**Comment by fieg** [comment]
Can you clarify your problem a bit more? What pre-loading technique are you using? Can you share some code?

**Comment by fieg** [comment]
Closing due to no response.
