### ISSUE TITLE
jQuery.noConflict() problem + fix

### ISSUE THREAD

**Issue by aXezilla** [webcreate/infinite-ajax-scroll#188]
Hi,

IASCallbacks.prototype.fireWith should not use the global jQuery when calling jQuery.Deferred(), this is causing problems when the plugin is used with jQuery.noConflict(true)

Best regards.

**Comment by fieg** [comment]
It is? I thought the noConflict mode only applies to $ variable...

**Comment by aXezilla** [comment]
If you pass true to jQuery.noConflict( [removeAll ] ) then it applies to the jQuery variable as well

**Comment by pbrisson** [comment]
Quick heads up on that - I'm also getting this error:

`Uncaught TypeError: Cannot read property 'Deferred' of undefined(…)`

... in callbacks.js line 132.

Changing it from:

`var deferred = $.Deferred();`

to:

`var deferred = jQuery.Deferred();`

... fix it in my case.

**Comment by fieg** [comment]
What is your jquery version?

**Comment by pbrisson** [comment]
v1.12.4

**Comment by fieg** [comment]
Hi, I release a new version v2.2.3 which fixes this issue. You can download it here: https://infiniteajaxscroll.com/download.html

Thank you for you time to report this issue. Please reopen this issue if you believe the issue is not fixed in the new version.
