### ISSUE TITLE
Reload content

### ISSUE THREAD

**Issue by popovae** [webcreate/infinite-ajax-scroll#190]
Hi!

Thank you for your plugin. I just started to test it to see if it will fit our project... So the main question for now is:

I have the following setup of IAS

```javascript
<script type="text/javascript">
	$(document).ready(function() {
		    var container = document.querySelector('#post-masonry');
		    var msnry = new Masonry( container, {
		      // options
		      itemSelector: '.post-item'
		    });
		
		    var ias = $.ias({
		      container: "#post-masonry",
		      item: ".post-item",
		      pagination: "#pagination",
		      next: ".next a",
		      negativeMargin: 1500
		    });

		    ias.on('render', function(items) {
		      $(items).css({ opacity: 0 });
		    });
		    
		    ias.on('rendered', function(items) {
		      msnry.appended(items);
		      msnry.layout();
		    });
		
			jQuery.ias().extension(new IASPagingExtension());
			
			jQuery.ias().on('pageChange', function(pageNum, scrollOffset) {
					event.url = event.url + "?page="+ pageNum;
			});
			
			 ias.extension(new IASSpinnerExtension());
		    
		    ias.extension(new IASHistoryExtension({
			//    prev: '.previous',
			}));
			
		    ias.extension(new IASNoneLeftExtension({html: '<div class="ias-noneleft" style="text-align:center"><p><em>You reached the end!</em></p></div>'}));
    });
  </script>
```

All the content is generated by PHP page where this code is located, so i have index.php and the Next page is index.php?page=2 and etc... everything works fine...
What I want to do next is somehow reload the content of the page current page (lets assume we have index.php?page=2&search=something, I want to get contents of index.php?page=1&search=somethingelse without page reload)
So I thought of some kind of workaround

```
function reload(){

		$('#pagelist').html('<a href="list.php?page=1&qsearch=some">next</a>');
		jQuery.ias().reinitialize();
		//the problem starts when you uncomment this line
		//$('#post-masonry').html('');
		jQuery.ias().next();
	}
```
It works perfectly - adds new content to the end of existing... BUT as soon as I uncomment $('#post-masonry').html(''); everything breaks... 
So, I can not get why it is happening? Maybe you have some Ideas or can advise easier way to do it?

**Comment by fieg** [comment]
Can you check that the `#pagination` element is not inside the `#post-masonry`? And what happens when you move the `$('#post-masonry').html('');` statement before the `reinitialize` call?

**Comment by fieg** [comment]
Closing due to no response.
