### ISSUE TITLE
Deleting hash in url

### ISSUE THREAD

**Issue by Sebazz** [webcreate/infinite-ajax-scroll#191]
Welcome,
 
I have some diferent problem i try to set up infinity scrolling at category pages. When i scroll down and content from second page is displaying i have that link:
https://antidotestreet.com/picknmix.html#/page/2
It's okay but if i will click on any product and back from list page i got 404 error. Why? Some script delete hash (#) from my link.
https://antidotestreet.com/picknmix.html/page/2 - 404
I don't know what script it is, i try to delete lot of script, with out reasons. Can somebody help me? I will be very pleased.
 
Best regards

**Comment by fieg** [comment]
This can be caused by any of one of the plugins you are running. Unless you believe it is caused by IAS we can't help you with solving this. 

btw. you are using a very old version of IAS which is no longer supported. Please upgrade to version 2.
