### ISSUE TITLE
Google Analytics tracking

### ISSUE THREAD

**Issue by ghost** [webcreate/infinite-ajax-scroll#2]
Allow to track pageviews for next pages with Google Analytics.

**Comment by tapankumar** [comment]
@fieg : Can you please confirm in which event, we should fire ga pageview event?

I am expecting some history event in which we should trigger ga pageview event when actual URL get change in browser.

**Comment by fieg** [comment]
This issue is old and was related to v1, but for v2 you can use the pageChange event of the Paging extension: https://infiniteajaxscroll.com/docs/extension-paging.html#pagechange
