### ISSUE TITLE
pages stop loading if no overflow is created after second one

### ISSUE THREAD

**Issue by manelis** [webcreate/infinite-ajax-scroll#201]
Hello,

I am trying to use ias in a case similar to this one:

http://infiniteajaxscroll.com/examples/overflow.html

The problem is that it is inside a resizable div, and the pages can vary in size, having just 50px height on the smaller case. The problem is if the div is bigger than the first 2 pages together, then no further pages will load.

Basically, imagine that the div has 300px height, the first page 200px, and the second one 50px. The plugin will load the first and the second page, however the 3rd will not load, because no overflow exists. If I resize the div (even at runtime) to be smaller than the 2 pages, then the 3rd one will load.

I do not know if this is a bug or a misconfiguration from my part.

Thank you for the help and if you need more concrete examples please ask. Showing directly is a bit hard given the context it is in.

**Comment by fieg** [comment]
Perhaps tweaking the [negativeMargin](http://infiniteajaxscroll.com/docs/options.html#negativemargin) can help here.

**Comment by manelis** [comment]
I dont exactly see how that could help, at least from what I understood that makes the oposite thing?

Im using 350 right now, but also happens with 0.

**Comment by manelis** [comment]
ok, to anyone that may want this, this can be fixed by adding self.scrollHandler() in line 553 here:

https://github.com/webcreate/infinite-ajax-scroll/blob/master/src/jquery-ias.js

 so this:

```javascript
    promise.done(function() {
      self.load(url, function(data, items) {
        self.render(items, function() {
          self.nextUrl = self.getNextUrl(data);

          self.resume();
        });
      });
    });
```

becomes this:

```javascript
    promise.done(function() {
      self.load(url, function(data, items) {
        self.render(items, function() {
          self.nextUrl = self.getNextUrl(data);

          self.resume();
          self.scrollHandler();
        });
      });
    });
```

**Comment by fieg** [comment]
I'm closing this issue because Infinite Ajax Scroll 2 [reached end of life](https://infiniteajaxscroll.com/blog/end-of-life-ias2/) and is being [superseded by v3](https://infiniteajaxscroll.com).

Suggestions given in this issue were taken into account when working on v3 and the issue should be resolved. If you have questions, feedback or think this issue was closed by mistake, please comment on this issue.
