### ISSUE TITLE
Problem with fixed DIV

### ISSUE THREAD

**Issue by demos77** [webcreate/infinite-ajax-scroll#205]
If i try to use IAS into an fixed DIV, it's don't work :(

i use position: fixed; and overflow-y: auto; so i have the scrollbar, but at the end (into the fixed div), the next page don't load.

Any idea ?

I have a sidebar with fixed CSS on the left and the content on the right.
on left i want an infinite scroll, and when we clic on an element, the right content change (ajax call).

**Comment by Bennith** [comment]
See link as i have the same issue...
http://jsfiddle.net/us2fre3g/9/

Seems that the page body needs to have scrollbars and then you need to scroll to the bottom of the fixed div, then the page body needs to scroll to kickstart the loading inside the fixed div..

Not ideal, not functional nor practical.

**Comment by Bennith** [comment]
Don't know why the developer would release it with this function not available, unless im missing something

**Comment by WisdomProductionz** [comment]
I'm having the same issues at the moment, next page not loading within a fixed div with overflow-y: scroll.
Is there a hack or solution to this issue?

**Comment by octoxan** [comment]
Same issue here, doesn't work at all in a fixed height div with overflow-y: scroll.

**Comment by robbiereynolds** [comment]
I'm loading results via ajax into a bootstrap modal window and the next page doesn't get triggered. I've also set the .modal-body to overflow-y: scroll. I've purchased commercial unlimited license, so please add support for this.

**Comment by fieg** [comment]
Infinite Ajax Scroll is definitely build to support scrolling in an overflow div. See this example: https://infiniteajaxscroll.com/examples/overflow.html

To make this work you need to initialize IAS with the container element, like this:

```js
var ias = $('#overflow').ias({...});
```

**Comment by Akshay-Hegde** [comment]
@fieg  is really example given in  `https://infiniteajaxscroll.com/examples/overflow.html` div scrolling working ?, I am on firefox , network  tab I see nothing its requesting with div scrolling, but  with `$.ias({...});` its requesting 

For example if you use below one it works, 
`
var ias = $.ias({...});
`


![document-overflow](https://user-images.githubusercontent.com/7464492/45820227-df95ea00-bcd5-11e8-9e86-92f0f14a6358.png)

But if you try to use div it doesn't


`
var ias = $('#overflow').ias({...});
`

![div-overflow](https://user-images.githubusercontent.com/7464492/45820230-e02e8080-bcd5-11e8-87c3-7dc41a95397d.png)

**Comment by fieg** [comment]
I just took a look and it seems broken indeed on latest Firefox 😢.

**Comment by fieg** [comment]
This issue is closed because Infinite Ajax Scroll 2 [reached end of life](https://infiniteajaxscroll.com/blog/end-of-life-ias2/) and is being [superseded by v3](https://infiniteajaxscroll.com).

Suggestions given in this issue were taken into account when working on v3 and the issue should be resolved. If you have questions, feedback or think this issue was closed by mistake, please comment on this issue.
