### ISSUE TITLE
Using the plugin via Browserify

### ISSUE THREAD

**Issue by adambirdie** [webcreate/infinite-ajax-scroll#206]
Hi there I am trying to add infinite-ajax-scroll via browserify but for some reason I keep getting the following error when trying to add the plugin as a "module".

I keep getting the following error:

> Uncaught TypeError: jqueryIas is not a function

Here is my file:

<addr>
    var $ = require('jquery');
    window.jQuery = $;
    global.$ = require('jquery');
    var jqueryIas     = require('../plugins/jquery.ias.min.js');
    
    var moduleListings = (function() {
    
        (function($tvshow_episode_listing){
    
            if($tvshow_episode_listing.length)
            {
                var ias = jqueryIas({
                    container:  '#tvshows-episodes-listing',
                    item:       '.m-listing-item-row',
                    pagination: '.m-pagination-tvshow',
                    next:       '.next-page-link'
                });
    
                ias.extension(new IASSpinnerExtension({
                    src: '/templates/default/images/loader.gif',
                    html: '<div class="ias-spinner l-listing-loading"><img src="{src}"/></div>'
                }));
    
                ias.extension(new IASNoneLeftExtension({
                    text: '',
                    html: ''
                }));
    
                ias.extension(new IASTriggerExtension({
                    offset: 1,
                    text: 'Load More Episodes',
                    textPrev: 'Load Previous Episodes',
                    html: '<div class="ias-trigger ias-trigger-next l-tvshows-listing-nav l-episodes-listing-nav l-tvshows-listing-nav-next"><a>{text} <em class="f-tvrocks icon-chevron-down"></em></a></div>',
                    htmlPrev: '<div class="ias-trigger ias-trigger-prev l-tvshows-listing-nav l-episodes-listing-nav l-tvshows-listing-nav-prev"><a><em class="f-tvrocks icon-chevron-up"></em> {text}</a></div>'
                }));
    
                ias.extension(new IASPagingExtension());
    
                ias.extension(new IASHistoryExtension({
                    prev: '.prev-page-link'
                }));
    
                ias.on('rendered', function() {
    
                    $('.ajax-watched-listing-toggle').off( "click");
                    toggle_watched_episode( $('.ajax-watched-listing-toggle') );
    
                    $('.tooltip').jBox('Tooltip', {
                        theme: 'TooltipDark'
                    });
                });
            }
        })($('#tvshows-episodes-listing'));
    
    });
    
    module.exports = moduleListings;
</addr>

Any ideas how I can require this plugin within browserify?

**Comment by fieg** [comment]
Rel #194

**Comment by jmartsch** [comment]
Any plans on fixing this? I try to do the same thing with webpack and also get the is not a function error.

**Comment by fieg** [comment]
Closing this in favour of #194 (duplicate issue)
