### ISSUE TITLE
Previous functions break on new page

### ISSUE THREAD

**Issue by adambirdie** [webcreate/infinite-ajax-scroll#209]
When my page loads my ajax functions work perfectly, but when a new page loads that previous page events stop working? I am reinitialising them on new page load for the new its which I presumed was correct? I am sure there is something simple I am missing but cannot see it here is my code:

    function init () {
        dropDownNav( $('.l-header-click-nav') );
        dropDownNav( $('.m-sidebar-nav-dropdown') );
        listing_action_btn($('.m-action-plus'));
        toggle_show( $('.ajax-follow-toggle') );
        toggle_watched( $('.ajax-watched-show-toggle') );
        toggle_watched_episode( $('.ajax-watched-listing-toggle') );
    }

    $(function () {

    init();

    (function($tvshows_listing){

        if($tvshows_listing.length)
        {
            /** Trigger Infinite Ajax Scroll **/
            var ias = jQuery.ias({
                container:  '#tvshows-listing',
                item:       '.l-tvshows-listing-item',
                pagination: '.m-pagination-tvshows',
                next:       '.next-page-link'
            });

            ias.extension(new IASSpinnerExtension({
                html: '<div class="ias-spinner m-listing-loading m-listing-tvshows-listing-loading"><div class="bounce1"></div><div class="bounce2"></div><div class="bounce3"></div></div>'
            }));

            ias.extension(new IASNoneLeftExtension({
                text: 'There are no more...',
                html: '<div class="ias-noneleft l-tvshows-listing-noneleft">{text}<em class="f-tvrocks icon-frown-o"></em></div>'
            }));

            ias.extension(new IASTriggerExtension({
                offset: 5,
                text: 'Load more',
                textPrev: 'Load previous',
                html: '<div class="ias-trigger ias-trigger-next m-listing-nav l-tvshows-listing-nav l-tvshows-listing-nav-next"><a>{text} <em class="f-tvrocks icon-chevron-down"></em></a></div>',
                htmlPrev: '<div class="ias-trigger ias-trigger-prev m-listing-nav l-tvshows-listing-nav l-tvshows-listing-nav-prev"><a><em class="f-tvrocks icon-chevron-up"></em> {text}</a></div>'
            }));

            ias.extension(new IASPagingExtension());

            ias.extension(new IASHistoryExtension({
                prev: '.prev-page-link'
            }));

            ias.on('rendered', function() {
                init();
            });
        }

    })($('#tvshows-listing'));
    });

**Comment by adambirdie** [comment]
Update*

Sorry to update so quickly but I managed to resolve it on desktop with the following but its doesn't work on IOS devices, it still removes all previous functions until the next page is loaded:

    ias.on('rendered', function() {

          $('.m-action-plus').off( "click");
          $('.ajax-follow-toggle').off( "click");
          $('.ajax-watched-show-toggle').off( "click");
          init();
    });

**Comment by adambirdie** [comment]
Got it working did the following:

      ias.on('rendered', function(items) {
                var $items = $(items);
                listing_action_btn($items.find('.m-action-plus'));
                toggle_show( $items.find('.ajax-follow-toggle') );
                toggle_watched( $items.find('.ajax-watched-show-toggle') );
            });

**Comment by fieg** [comment]
Glad to hear you worked in out! :+1:
