### ISSUE TITLE
spinner and load more button position

### ISSUE THREAD

**Issue by mmjaeger** [webcreate/infinite-ajax-scroll#211]
Hello
Love the script - thank you for your work - I've a suggestion based on the experience adding the script to my pages - I think it is a bad idea to add spinner and buttons to the container that actually holds the ajax items - I'm using flexbox with some styling like nth-child.. and it all affects (background-color, width, etc.) the spinner and the buttons placed by the script - why not place them in a separate container after the items container??

Thanks

**Comment by fieg** [comment]
Nice suggestion, thank you. I'll keep it in mind for future releases.

**Comment by fieg** [comment]
Closing this one in favour of #215 (duplicate issue)
