### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by ghost** [webcreate/infinite-ajax-scroll#212]
I am using jquery-ias.min.js for producing an infinite scroll in my page but the plugin is not functional at all. Any help is much appreciated.
http://jsfiddle.net/b45rfmdn/

**Comment by Bennith** [comment]
I have this issue aswell...
I think it has to do with the overflow div being bigger (height) than the page body (if the body content is bigger than the screen size when createa a scrollbar (or style="height:2500px;overflow-y:auto;"))..

For now i can only get the infinite scroll to trigger when the body is bigger than the overflow div and only once the overflow div is scrolled to the bottom and then the page body scrollbar scroll is activated.

http://jsfiddle.net/us2fre3g/9/

**Comment by fieg** [comment]
I just release v2.2.2 which has fixes for running IAS in an overflow div. Let me know if the problem still exists with this new version. Closing this for the time being.
