### ISSUE TITLE
Reinitialize IAS after new ajax content

### ISSUE THREAD

**Issue by mmjaeger** [webcreate/infinite-ajax-scroll#213]
Hello
I was looking everywhere to find a solution but couldn't really find anything - could anybody please tell me what the proper solution is to destroy/reinitialize IAS after some new AJAX content was loaded - is there some sample code somewhere how to do this?

Thank you in advance for your input.

**Comment by Bennith** [comment]
Maybe...
jQuery.ias().reinitialize(); 
and/or..
jQuery.ias().unbind();
see docs at http://infiniteajaxscroll.com/docs/methods.html
