### ISSUE TITLE
Trigger extention append

### ISSUE THREAD

**Issue by perlarenee** [webcreate/infinite-ajax-scroll#215]
Hi. 
Something that has caused a bit of trouble for me integrating this with isotope masonry js is that there's no option to select a container to append the trigger, spinner and no posts left messages to separately from the main container. 
When using masonry with the existing code, the trigger ends up inside the masonry container, which messes with the styling. 
This could be avoided by providing an additional parameter that accepts another div id to those extensions and then appending the text and spinner to that element instead of the main container.
-R

**Comment by gakuranman** [comment]
I have the same issue. I'm having to work around it with absolute positions and negative margins, but it would be so much easier if we could define where the triggers (next and previous) get appended. There needs to be an option to append these triggers outside the main container to avoid conflicting with the isotope absolute styling.

**Comment by perlarenee** [comment]
hi. i went ahead and branched it and added the additional options for trigger, noneleft and spinner extensions: https://github.com/perlarenee/infinite-ajax-scroll Not sure whether it's something they'd want to pull in or not so am just including a link here for others' use. The only files that were changed were the extension files and relevant doc files.

**Comment by fieg** [comment]
If you can do a PR we can have a look at your solution. Adding options for container sounds like a good one.

**Comment by perlarenee** [comment]
Hi. Okay. The downside I think would be people needing to remember to fill out the additional parameters on the extensions. I didn't have time to do it, but if the main 'container' parameter could be used as the default for each extension, it would make it behave as it does now if nothing unique is specified.

**Comment by fieg** [comment]
This issue is closed because Infinite Ajax Scroll 2 [reached end of life](https://infiniteajaxscroll.com/blog/end-of-life-ias2/) and is being [superseded by v3](https://infiniteajaxscroll.com).

Suggestions given in this issue were taken into account when working on v3 and some are even implemented. If you have questions, feedback or think this issue was closed by mistake, please comment on this issue.
