### ISSUE TITLE
Pagination script for ias

### ISSUE THREAD

**Issue by willw2015** [webcreate/infinite-ajax-scroll#216]
Hi, can anyone recommend a pagination script that works well with ias, I have an issue when using the pagination script from http://www.phpeasystep.com/phptu/29.html - I have posted this on stackoverflow at http://stackoverflow.com/questions/32395627/infinite-ajax-scroll-pagination-looping

**Comment by andrewblake1** [comment]
Have you solved? That script is difficult to step thru visually - massive overkill if you are just wanting it for this infinite scroll plugin.

Perhaps just something that produces:
```
<div class="pagination">
    <a class-"next" href="http//your_next_page.php"></a>
</div>
```
only when there is a next page, e.g. (untested and written while on first coffee so hopefully close):
```
<?php
$thisPage = isset($_GET['page']) ? $_GET['page'] : 1;
$nextPage = $thisPage + 1;

// since it appears select count is giving number of pages rather than number of items to display
$query = $pdo->prepare("select count(*) from table where...");
$query->execute(array(':id' => $id));
$totalPages = $query2->fetchColumn();

$pagination = $thisPage < $totalPages
    ? "<div class=\"pagination\"><a class=\"next\" href=\"home.php?page=$nextPage\"></a></div>"
    : '';
```

**Comment by fieg** [comment]
Closing this as server side pagination is outside of the scope of Infinite AJAX Scroll. 

@andrewblake1 thank you for helping out!
