### ISSUE TITLE
Feature request re: prev

### ISSUE THREAD

**Issue by andrewblake1** [webcreate/infinite-ajax-scroll#220]
Would be great to see prev dealt with in same way as next in general so that when returning back to or heading straight to a specific page there is the ability for endless scroll upwards as well as downwards. My use case is in scheduling hence ability to jump to next year and endlessly scroll forward but also needed to allow user to move back. I have seen another issue or 2 here where people have mentioned going back to the page they were on but having lost the previously loaded data they had scrolled from.

I have fixed this myself if anyone else wants me to post my code at any time - by overriding IASHistoryExtension.prototype.prev.

With trigger and history extensions the link to click above appeared which is fine though I wanted endless scroll not click and scroll. Solution was simple i.e. hide the trigger text for previous but activate at scroll top for the container - adjusting scroll position for new content so users scrolls up rather than position at top of new content.

**Comment by WisdomProductionz** [comment]
Hi, i have been looking for a way to fix this issue, but so far unsuccessful. Could you please post your code

**Comment by andrewblake1** [comment]
Sure, is your purpose for returning from another page or for general endless scroll in both directions for something time based perhaps? Reason is, the hack works for scrolling both directions but is untested with returning to screen so you might have more work to do.

Just checking it now to remove a couple of other things like a pjax related hack.

**Comment by WisdomProductionz** [comment]
Thank you for the quick response.
Well when i click back lets say i land on page 4 and i scroll up i have to click the prev button to load the previous content, which is quite a pain. I was wanting to eliminate the prev button and load all the previous content when i come back to the page, so i can scroll without having to click load previous.

**Comment by andrewblake1** [comment]
Yeah, If I recall, it wasn't too difficult to get it it to do what you want, My problem was stopping endlessly pulling in all the previous data which is a problem if people jump a year a head in my system. Wanted to pull in a page at time when the reached scroll pos 0.

Will look thru my code for the relative parts. Its been a few days but will try to help apply the relevant parts of mine to yours.

Since you have the link showing, hide the link first with css.

More following ..

**Comment by andrewblake1** [comment]
add this to your javascript file I think - sorry just looking thru the code for the bits you will probably need
```
function iasPrev() {
    if ($('.pagination .prev').length) {
        $('.ias-trigger-prev').click();
    }
}
```
more following ...

**Comment by WisdomProductionz** [comment]
I also came across that, i had it working a little but when i came back to so page 4 it was pullin me up the pages till i reached page 0.

Thank you for your help, i will apply the changes now

**Comment by andrewblake1** [comment]
add these too
```
function scrollPagerScroll(scrollOffset, scrollThreshold) {
    if (($.ias().$scrollContainer.height() - scrollOffset) == 0) {
        $.ias().reinitialize();
        iasPrev();
    }
}

$(window).load(function() {
    iasPrev();
});

```

**Comment by andrewblake1** [comment]
And the guts of it ... note the deliberately commented out line and remark towards the bottom.

Also you will notice a tiny jump as the spinning wheel displays and is removed - I havn't bothered fixing that as a low priority for me - will do some stage - won't be difficult.

An issue you may have already found to is that content is append but the scroll positions jumps to the top of that as the page is added (well it was for me anyway), so I had to adjust the scroll position as the elements were added to keep it back in the position of where the user had landed if that makes sense.

BTW, where are you located - country.

```
$(document).ready(function() {
    IASHistoryExtension.prototype.renderBeforeScroll = function (items, callback) {
        var ias = this.ias,
            $firstItem = ias.getFirstItem(),
            count = 0, scrollHeight = 0;

        ias.fire('render', [items]);

        $firstItem.before(items);

        $(items).each(function() {
            scrollHeight += this.scrollHeight;
        });

        if (!$(items).length) {

            ias.fire('rendered', [items]);

            if (callback) {
                callback();
            }
        }

        $.each(items, function () {
            if (++count < items.length) {
                return;
            }

            ias.$scrollContainer.get(0).scrollTo(0, scrollHeight);

            ias.fire('rendered', [items]);

            if (callback) {
                callback();
            }
        });
    };

    /**
     * Load the prev page. Altered to use renderBeforeScroll defined above.
     * Also needed to re-read the previous url as the plugin by defualts gets this on initialization which doesn't
     * suite our purpose of having links to next and prev and a use query paramater so that can fully re-build the
     * pagination properly each time.
     *
     * @public
     */
    IASHistoryExtension.prototype.prev = function () {
        var url = $('.pagination .prev').attr('href'),
            self = this,
            ias = this.ias;

        if (!url) {
            return false;
        }

        ias.pause();

        var promise = ias.fire('prev', [url]);

        promise.done(function () {
            ias.load(url, function (data, items) {
                self.renderBeforeScroll(items, function () {
                    self.prevUrl = self.getPrevUrl(data);

                    ias.resume();

                    if (self.prevUrl) {
                        // A Blake - block endlessly scrolling back in time after first activation
//                        self.prev();
                    }
                });
            });
        });

        promise.fail(function () {
            ias.resume();
        });

        return true;
    };
});

```

**Comment by andrewblake1** [comment]
Basically, make sure the prototypes are overriding the plugins prototypes and actually running instead of the historyextension originals.

Note the call to iasPrev on window load i.e. after everything else is initialized I call iasPrev (just check your selectors are correct in there) and am just activating a click on the invisible element which sets the process in motion.

The prototype extensions take care of most of it, but note that scrollPagerScroll is scroll event handler so you will need to set that as the event handler for the scroll event when initializing the plugin.

**Comment by andrewblake1** [comment]
Theres no doubt a way easier way, but my jquery knowledge isn't spectacular so hacked this into submission - was a battle with my limited knowledge. The plugin is great and obviously very cleverly written - a bit beyond me, but got there in the end - for now anyway until find a bug.

**Comment by WisdomProductionz** [comment]
Thank you for your code, i really appreciate it, im not a javascript expert either lol. I cant seem to get it to work though. Here is my code so far.

```
var ias = jQuery.ias({
        container:  '#infini-scroll',
        item:       '.posts',
        pagination: '#pagination',
        next:       '.next a'
    });

ias.extension(new IASPagingExtension());

ias.extension(new IASTriggerExtension({
        htmlPrev: "<a>Load previous status's</a>",
        html: "<a>Load more status's</a>"
    }));

ias.extension(new IASSpinnerExtension({
        src: globalUrl+'webroot/img/ajax-loader.gif'
    }));

function iasPrev() {
        if ($('.pagination .prev a').length) {
            $('.ias-trigger-prev').click();
        }
    }

    function scrollPagerScroll(scrollOffset, scrollThreshold) {
        if (($.ias().$scrollContainer.height() - scrollOffset) == 0) {
            $.ias().reinitialize();
            iasPrev();
        }
    }

    $(window).load(function() {
        iasPrev();
    });

IASHistoryExtension.prototype.renderBeforeScroll = function (items, callback) {
        var ias = this.ias,
            $firstItem = ias.getFirstItem(),
            count = 0, scrollHeight = 0;

        ias.fire('render', [items]);

        $firstItem.before(items);

        $(items).each(function() {
            scrollHeight += this.scrollHeight;
        });

        if (!$(items).length) {

            ias.fire('rendered', [items]);

            if (callback) {
                callback();
            }
        }

        $.each(items, function () {
            if (++count < items.length) {
                return;
            }

            ias.$scrollContainer.get(0).scrollTo(0, scrollHeight);

            ias.fire('rendered', [items]);

            if (callback) {
                callback();
            }
        });
    };

    /**
     * Load the prev page. Altered to use renderBeforeScroll defined above.
     * Also needed to re-read the previous url as the plugin by defualts gets this on initialization which doesn't
     * suite our purpose of having links to next and prev and a use query paramater so that can fully re-build the
     * pagination properly each time.
     *
     * @public
     */
    IASHistoryExtension.prototype.prev = function () {
        var url = $('.pagination .prev').attr('href'),
            self = this,
            ias = this.ias;

        if (!url) {
            return false;
        }

        ias.pause();

        var promise = ias.fire('prev', [url]);

        promise.done(function () {
            ias.load(url, function (data, items) {
                self.renderBeforeScroll(items, function () {
                    self.prevUrl = self.getPrevUrl(data);

                    ias.resume();

                    if (self.prevUrl) {
                        // A Blake - block endlessly scrolling back in time after first activation
//                        self.prev();
                    }
                });
            });
        });

        promise.fail(function () {
            ias.resume();
        });

        return true;
    };

    jQuery.ias().initialize();
```

Any help would be really appreciated. I'm located in United Kingdom

**Comment by andrewblake1** [comment]
Saw then nz and thought you might have been in New Zealand too.

Would have been surprised if it worked that easy for you - the code does work for me, but is based around my setup.

I will take a look now at your code.

**Comment by andrewblake1** [comment]
OK, forgive me if I am wrong here.

First you do need to add the scroll event handler in as scrollPagerScroll - where you create the ias object i think.

Next I can't see a call to attach the history extension - which should come after the definittion of the prototype extensions some probalby just before your initialization.

**Comment by WisdomProductionz** [comment]
Sorry for late reply, was nearly 6 in the morning here in the Uk so had to sleep. Thank you for the help so far but i have a couple of questions, where abouts do i add the scrollPagerScroll handler?. I have never used prototype before but i think there might be some conflicts between jquery and that

**Comment by andrewblake1** [comment]
Figured your programming time for uk was rather late.

I'll do my best but don't take everything I say as necessarily being correct - its just my current best understanding.

Not talking about prototypejs the language, but about prototype as an integral part of javascript. Every object in javascript, extends from another object in javascript. An inheritance mechanism similar to classes and sub classes in other languages except talking about extending instantiated objects as opposed to classes if that makes sense - try googling it. Perhaps think of functions attached to objectname.prototype as being public functions that can be overwritten if necessary before you recreate a new object, using that object as a template for the new once and so on. Jquery itself makes heavy use of it though I don't completely understand it by I think .fn is just an alias for prototype i.e. when you call $.fn.something you are calling a prototype function and attaching to $.fn is extending the jquery prototype for your later user.

Anyway I will put up what I see here now is missing.
Add this - anywhere after the object is created, perhaps just before you initialize it.
```
...
// attach the scroll event handler
ias.on('load', scrollPagerScroll);

// attach the history extension
ias.extension(new IASHistoryExtension());
```
So in summary in order that I can make easier use of updates to the extension in the future, as opposed to forking the repository and making changes to the code which becomes a merging headache in the future, I found a publicly exposed function in the history extension that allowed me to alter how the history extension behaves - this is the reason why the plugin author made it like that i.e. to allow people to alter and extend the functionality like this.

I hope this works for you. Am not sure that there is much more to try, but it definitely wouldn't work without the above lines as I didn't see the history extension attached which is what my code attaches to.

And also the event handler needed to be attached in order to cause a faked click event on the invisible link everytime the container gets to the top.

Other than that there isn't too much to the changes. You may run into difficulty perhaps when new content is attached as to how the plugin is initiialized/re-initialized, but you can only get around this with a debugger - if not familiar with developer tools in chrome or firebug then you will probably need to be in order to step thru and see where it goes wrong for you.

Am happy to try and answer anything else, but if the above doesn't work, stepping thru is necessary.

**Comment by andrewblake1** [comment]
Just be sure to put those new lines just before
```
 jQuery.ias().initialize();
```
as if you attach the history plugin first before the new prototype extensions then the new extensions won't be part of the history object you have just attached to ias

**Comment by WisdomProductionz** [comment]
Thank you for all the help andrew, i really appreciate it. I have followed all the advice you have given me, i have it kind of working now. when i scroll up it loads the last previous page but after that it will just keep loading the same page over and over. I have tried a few things to fix this as i know it will be something small but for the life of me i cant figure it out.

**Comment by andrewblake1** [comment]
I generate my own prev link, each time (I need to because it is time based rather than page based) - can't remember but suspect the plugin probably creates its own automatically perhaps?

Try replacing the code at the top of IASHistoryExtension.prototype.prev with,
```
IASHistoryExtension.prototype.prev = function () {
  var url = this.prevUrl,
      self = this,
      ias = this.ias;
...
```
That is taking it back to the original. I needed to re-read the url from my own newly brought in pagination item that simply contains a next and previous link ... becuase it is time based my pages are approximately 20 items long and terminating on the nearest date boundary past 20 if 20 exist.

In your situation, the plugin might be creating the link so it might work just to go back to the original code for that bit as above.

In either case (your prev link like me, or plugin generated prev link), check in your debugger for the prev link, and step thru to find out what the url is at that point in the code - i.e. put a breakpoint on the ias.pause line in my prototype.prev function and examine the url. Thats the data its pulling.

**Comment by andrewblake1** [comment]
I should add that, I found that the history extension in the area indicated above was using the prev link it got when initialized rather than re-reading each time the plugin entered that area of code hence the reason I picked up the href from the pagination prev myself

**Comment by WisdomProductionz** [comment]
That was the problem, i just needed to change the code you wrote above. Thank you so much for the advice, help and keeping with me, i really appreciate it. I can finally relax now lol. The plugin is excellent but this is something that should be an option (off for default) for people to use whether they do or don't.

**Comment by andrewblake1** [comment]
Yip, agreed - hence why I raised as feature request here.

If you can afford to by a license for it (just 3 or 4 pints) then would recommend doing it (I did) in order to keep the plugin author motivated to keep improving the product.

My code is fairly "Wanky" (to use the plugin authors own terminology I saw somewhere), and there is undoubtably a simpler way to do this - it just never sprung out at me.

Wouldn't be surprised with the level of hacks I did here if something else breaks somewhere but all good for now.

Glad you got it sorted.

Cheers
Andrew

**Comment by WisdomProductionz** [comment]
I do plan on buying a licence before i launch what i hope will be a commercial site. Having the code you have provided that gives this plugin scrolling backwards functionality has made it an easy choice of which plugin to go far. There is just one last question i have, i am using the negativeMargin scrolling down setting but is there anyway to have the same going up?

I tried changing the scrollHeight but that didn't solve the problem

**Comment by andrewblake1** [comment]
There will be a way of course, I intend to look into that at some stage, to be honest wan't sure that negative margin was working in mine, but hadn't really looked into it. I just need it to work for now, and improvements like that come come later. When I do it, I will post it here.

Basically my changes check for scroll offset to be at the top of the div and then triggers click, am guessing could simply add the negative margin amount i.e. if offset from top is effectively 0 to trigger the prev click, then instead do it at say 100 px so every time get to 100px from top then it would trigger.

Should be simple enough but havn't looked yet.

**Comment by amdad** [comment]
This issue is Open, so auto prev feature is still missing?

**Comment by rsambhangi** [comment]
Any update on when this feature  will be available and part of the extensions?

**Comment by Messa1** [comment]
Any Update?

**Comment by fieg** [comment]
I have worked on this feature in the past, but as easy as it seems, it has [drawbacks](https://github.com/webcreate/infinite-ajax-scroll/issues/274#issuecomment-312121157) and I couldn't get it right from a User Experience point of view. 

Unless some other javascript expert can come up with a PR that works, don't expect this feature to be added to IAS.

**Comment by fieg** [comment]
Closing in favor of #274
