### ISSUE TITLE
Problem if using it with PHP/MySQL

### ISSUE THREAD

**Issue by saturnus69** [webcreate/infinite-ajax-scroll#221]
I would like to use it with Data from MySQL, like this:
http://www.w3bees.com/2013/09/jquery-infinite-scroll-with-php-mysql.html

It works, but something is strange:
If i take a look at the source, only the first set of data is there, no matter how many times I've scrolled!
jQuery/Ajax works only in the first set of data (like "$(".btn-item").click(function() {...").
Does somebody know why and how i can fix it?

Contents after scroll are not in the source-code-view...
http://infiniteajaxscroll.com/examples/basic/page1.html
SEO Friendly?

**Comment by fieg** [comment]
New items are dynamically added with javascript. Seach engines don't use javascript and visit your site page by page, so they can view the source-code.
