### ISSUE TITLE
data display unnormal

### ISSUE THREAD

**Issue by sandy0201** [webcreate/infinite-ajax-scroll#222]
Hi,

Please refer to https://github.com/kop/yii2-scroll-pager/issues/40 for the full issue.
When the page reloads the content, the scroll pager doesn't work anymore, it either only displays the last page or the first page, and as you scroll to the end of that specific page, it doesn't load anymore (doesn't load any other pages that there is), can't go back or forward.

Please assist urgently.

Thank you.
Kind regards.

**Comment by fieg** [comment]
> is there any way to re-attach the JavaScript events? Like is there any JavaScript function I can call to re-attach the Scroll Pager events to make it work?

Yes, `reinitialize`. Please read the docs for more information.
