### ISSUE TITLE
Trigger Extension: Add a nice preloader until the next page loads/between page loads

### ISSUE THREAD

**Issue by pseudonymus** [webcreate/infinite-ajax-scroll#223]
Hi guys,

I`m using this awesome plugin with the trigger extension activated. 

When I click on the Load More button, it simply disappears and appears only after the new page loads. 
Is there any way of adding a nice preloader/spinning wheel or simply manipulate the Load More button in a way between the page loading times?

Thanks!

**Comment by fieg** [comment]
Also activate the spinner extension and it will show a spinner.

**Comment by pseudonymus** [comment]
Thanks for letting me know!
