### ISSUE TITLE
TriggerExtension reinitialize after click to have a infinite scroll again for the next pages

### ISSUE THREAD

**Issue by kaiserlos** [webcreate/infinite-ajax-scroll#224]
As example at the moment I have a offset of 3, so after 3 pages I have to click the "next link".
After that I have to click again on the next link for every next page.
I would love to reset the count so I can infinite scroll again 3 more pages and the next "next link" only comes after page 6...

Any easy way?

**Comment by fieg** [comment]
No easy way. But IAS is extendable via plugins. You can copy the trigger extension and modify it for your own needs.
