### ISSUE TITLE
Not loading new content after loading one page, (Pagination not updating)

### ISSUE THREAD

**Issue by athar21200** [webcreate/infinite-ajax-scroll#227]
Hello,

I have spent my whole night to get ride from the issue.
It is unaccepted issue,

Plugin load content when scroll down but it load only one time and don't work after that. I deeply study each and every thing and found that it is not updating pagination class to new link.

Please let me  know if someone can help here.

**Comment by mheiduk** [comment]
Hi,

are you using a CMS? I implemented it in a custom theme in Wordpress and its working fine, maybe I can help, but I need further information.

br,
Marc

**Comment by athar21200** [comment]
I am using OSclass (Open source),

**Comment by bschelling** [comment]
probably the next url needed to load the next page is not found. 

```
the basic example uses 
var ias = $.ias({
  container:  ".container",
  item:       ".item",
  pagination: "#pagination",
  next:       ".next a"
});
```

but the selector in this.getNextUrl can't find it that way, at least for me
$(".next a") is an empty array. havent investigated it further, just use a class for your nextlink you don't use anywhere else on the page, eg

  `next:       ".IASnextclass"`

 hth

**Comment by fieg** [comment]
Seems like a configuration/implementation error, not an actual bug in IAS.
