### ISSUE TITLE
Bower install issue

### ISSUE THREAD

**Issue by 10SexyApples** [webcreate/infinite-ajax-scroll#229]
When I install with bower install --save infinite-ajax-scroll ... and set up my javascript to call ias ...  I get "Uncaught ReferenceError: IASCallbacks is not defined".

Looking into it I see that callbacks.js isn't even loading ( via wiredep ). I looked into ias' bower.json file as well as the ias component directory structure and I notice that there is no dist directory and that the main include doesn't reference the callback.js file, which I believe is creating that error.

I did a little digging and discovered that it would be best to just load the ias minified version which included callback.js, so, I would normally do this in an override in my bower.json and just call your dist/minified file, but, like I said, it isn't there because the dist directory is set to ignore in ias' bower.json 

Any way you guys could possibly not ignore that .dist file so folks like myself can just easily override and call the necessary files ( minified in this case ) to make IAS work out of the box when using bower and gulp w/ wiredev?

Also wanted to let you guys know that using bower install --save infinite-ajax-scroll creates the following entry in my auto created bower.json file ... is the # intentional? I can't find any documentation on what that does ... clues? ;-)
"jquery-ias": "infinite-ajax-scroll#~2.2.1"

UPDATE: created my own temporary dist directory in your bower component and put your jquery.ias.min. js in it and did an override in my bower.json to only load this file and now I have no console errors and everything is loading as expected ... but, obviously, I can't use my wiredeps to update this way, so, still hoping you guys will go ahead and not ignore that dist directory ;-)

**Comment by 10SexyApples** [comment]
This shouldn't necessarily be here ... I'll let you guys decide ... I'm also trying to now implement ias with isotope filtering of a vertical list of items like this ... 

// Infinite Ajax Scroll with consideration for Isotope

      ```
  var elem = document.querySelector('#isotope-list');
        var iso = new Isotope( elem, {
          // options
          itemSelector: '.hentry',
          layoutMode: 'vertical'
        });



        var ias = $.ias({
          container:  "#isotope-list",
          item:       ".hentry",
          pagination: ".navigation",
          next:       ".nav-previous a",
          delay:      1200,
        });

        ias.on('render', function(items) {
          $(items).css({ opacity: 0 });
        });

        ias.on('rendered', function(items) {
          iso.appended(items);
        });

        ias.extension(new IASSpinnerExtension());
        ias.extension(new IASTriggerExtension({offset: 2})); // shows a trigger after page 2
        ias.extension(new IASNoneLeftExtension({html: '<div class="ias-noneleft" style="text-align:center"><p><em>You reached the end!</em></p></div>'}));

```

It's "kind of" working but the most important functionality ( the google way of doing infinite scrolling ) vanishes ... there is no more page identification when scrolling and using the isotope filters and when an isotope filter is clicked isotope has no idea where to load the content ... big spaces where the previous content remain ( I"m guessing because this is appending to previously existing content ) ... and the navigation doesn't know where to go either ( click more link ) ... it appears to just go to top of parent div behind the isotope/infinite-ajax-scroll div. 

I see that there is a lot of interest in getting this working now since Masonry is no more, so, perhaps someone could help me get it sussed out and I'll help spread the word on how to implement it cleanly over on StackOverflow ... or perhaps I should just post this over there?

**Comment by fieg** [comment]
We do not provide a dist in de repo at the moment. It's something I have to look into.

The missing callbacks.js could be fixed by adding it to the main directive of bower.js, I think. I'll look into it when I have some time, or perhaps you could send a PR.

**Comment by fieg** [comment]
I finally looked into this. This is what I found out:

Adding callbacks.js to the main directive is not allowed (only one file per file type is allowed). Also as far as I can read on the Bower website, the "main" directive is not actually used. So when installing with Bower you have to include the scripts yourself. And in that case you must not forget to include callbacks.js. [I wrote some new documentation on installation with Bower](https://github.com/webcreate/infinite-ajax-scroll/pull/253)

> Also wanted to let you guys know that using bower install --save infinite-ajax-scroll creates the following entry in my auto created bower.json file ... is the # intentional? I can't find any documentation on what that does ... clues? ;-)
> "jquery-ias": "infinite-ajax-scroll#~2.2.1"

I think this is some sort of alias. Infinite AJAX scroll is know as "jquery-ias", as well as "infinite-ajax-scroll" in Bower.

**Comment by fieg** [comment]
This issue is closed because Infinite Ajax Scroll 2 [reached end of life](https://infiniteajaxscroll.com/blog/end-of-life-ias2/) and is being [superseded by v3](https://infiniteajaxscroll.com).

If you have questions, feedback or think this issue was closed by mistake, please comment on this issue.
