### ISSUE TITLE
Trojan: Win32/Spursint.A ?

### ISSUE THREAD

**Issue by rmff** [webcreate/infinite-ajax-scroll#234]
Cloud someone check if the file for download (http://infiniteajaxscroll.com/jquery-ias.min.js) has some trojan?

Windows Defender detect [this] (http://www.microsoft.com/security/portal/threat/encyclopedia/entry.aspx?name=Trojan%3aWin32%2fSpursint.A&threatid=2147705703&enterprise=0)
Trojan: Win32/Spursint.A

**Comment by fieg** [comment]
Did a quick look and I don't see any malicious code.

**Comment by rmff** [comment]
I did too, any thing that could be suspicious to Defender is the embed 
image... maybe a false positive.
