### ISSUE TITLE
Reinitialize on new content

### ISSUE THREAD

**Issue by BjoBre** [webcreate/infinite-ajax-scroll#235]
Hi,

maybe it's just an understanding trouble:
I've got a list of elements which are paginated. Above the list the user is able to choose between 2 filters, that will update the list and cause an ajax-request. Current my JS looks like (abstract):

```javascript
var myExtension = {
  initIas: function() {
      myExtension.options.ias = $.ias({
          container: '.list',
          item: '.item',
          pagination: '.pagination',
          next: '#nextLink'
      });
  },
  init: function() {
        myExtension.initIas();
        $('select').on('change', function(e) {
              e.preventDefault();
              $.ajax({
                  url: 'index.php',
                  type: 'GET',
                  [...],
                  success: function(result) {
                      myExtension.options.ias.destroy();
                      myExtension.options.list.html(result);
                      myExtension.options.ias.bind();
                  }
              });
        }
  }
};
myExtension.init({[...]});
```

The result, given by the ajax call, is an updated list with its own pagination.

Now I've got the problem, that "nextUrl" inside IAS still has the old href of the pagination. That means, if the list already shown Page1, Page2 and Page3, it will continue with Page4 for the reloaded content. I also realised, after calling "destroy()", that the variable is still the same. 
I also tried to reinitialize IAS (instead of destroy() and bind()) without a successfull result. 

So the question is: How can I reinitialize IAS or is it not possible in my case?

**Comment by fieg** [comment]
Calling reinitialize after the html is updated should work.

**Comment by BjoBre** [comment]
Sadly this doesn't work as well. I already tried it. 
After the new content is loaded the pagination is visible and the script is executed, but the "nextUrl" is still the same as before.

**Comment by fieg** [comment]
You say:

> After the new content is loaded

But are you sure you the `#nextLink` element is also updated with a new url?

Can you make a jsfiddle which shows the problem?

**Comment by fieg** [comment]
Closing due to no response.
