### ISSUE TITLE
ias stops loading page after 3 loadings

### ISSUE THREAD

**Issue by julienrondeau** [webcreate/infinite-ajax-scroll#236]
Hello

I'm using wordpress 4.2.2 and last version of ias.

I'm using a text link to l oad the next page.
the plugin works fine on the first 3 loading, and at the third time, it stops loading and stay on the spinner.
in the console it says : "GET http://(url of my site)/page/4/ 404 (Not Found) - jquery-1.12.2.min.js:4 "

my init is: 

> var ias = $.ias({
  container:  '.site-main-content',
  item:       '.post',
  pagination: '.navigation',
  next:       '.nav-previous a',
  delay: 1000
});

>  ias.extension(new IASTriggerExtension({
    text: 'SHOW MORE PUBLICATIONS',
    offset: 1
  }));
  ias.extension(new IASSpinnerExtension());
  ias.extension(new IASNoneLeftExtension({text: 'No more publications'}));

Any help ?

**Comment by fieg** [comment]
Your next link (`.nav-previous a`) should not lead to a 404 page. Remove the next link element if there is no next page.

**Comment by julienrondeau** [comment]
ok. 
But how do I remove the next link element then?
 I thought 
> ias.extension(newIASNoneLeftExtension({text: 'No more publications'}));

would the job?

**Comment by julienrondeau** [comment]
and after different tests, the problem starts each time at the third loading...
impossible to load more than 3 times !?

is it a bug? or a configuration issue ?

**Comment by julienrondeau** [comment]
Ok Problem solved.

The issue came from the $WP_query I used in my template in order to display only 6 posts per page.
I removed that query and everything went right.

thanks anyway.

**Comment by fieg** [comment]
:+1:
