### ISSUE TITLE
How to resolve FAQ #1?

### ISSUE THREAD

**Issue by johncave** [webcreate/infinite-ajax-scroll#237]
I'm using this plugin with Masonry to load a continuous wall of images and am running into FAQ issue number 1; every single page is being loaded as soon as the homepage is opened, leading to a ~15MB page currently. Given that the site is using Bootstrap and there is no way to know the height images will have at the frontend, I cannot workaround it by setting the height attribute. I'm currently using this code with the plugin http://imagesloaded.desandro.com to try to use the second workaround, but am still having the same issue.

```
$("#images-wall").imagesLoaded().done( function() {
var ias = $.ias({
      container: "#images-wall",
      item: ".home-thumb",
      pagination: "#paginator",
      next: "#next-page"
    });


    ias.on('render', function(items) {
      $(items).css({ opacity: 0 });
    });

    ias.on('rendered', function(items) {
      grid.masonry('appended', items);
    });

});
```

Site: https://www.yuriplease.com (Potentially NSFW)
How should I go about using the second workaround if it doesn't work like this?

**Comment by johncave** [comment]
Additionally to this I've noticed that the images of the second page are overlaid on the images of the first, but invisible, so clicking an image on the 'first page' will open a seemingly random image from the 'second page'. Only the second page loads incorrectly, subsequent pages load their images correctly onto the end of the div.

**Comment by fieg** [comment]
One thing I can think of is to [reinitialise](http://infiniteajaxscroll.com/docs/methods.html#reinitialize) IAS in the [rendered](http://infiniteajaxscroll.com/docs/events.html#rendered) event. But I'm absolutely not sure if this could work tho.

**Comment by jbeyer05** [comment]
@johncave you seem to have figured out the issue.  Do you recall the fix?  I'm looking at your live site, and my code mirrors yours precisely.  But I'm still experiencing "aggressive" fetching by IAS.

**Comment by johncave** [comment]
@jbeyer05 I fixed it by ripping apart IAS's method for detecting how far down the div is scrolled and replacing it with a new one. IAS is designed to work on a div that stays stationary within the page, with the scrolling happening within the div. I replaced the code that calculates this and replaced it with one that figures out how far from the bottom the entire page is scrolled, which fixed my exact issue. Will be able to send the exact code in an hour or two if you're unable to find the correct lines.

**Comment by jbeyer05** [comment]
Thanks @johncave , I thought I saw that you had done that, but wasn't sure.  I think I can track what you did from here, but thanks very much for the offer of further assistance!  I appreciate you getting back to me so quickly.

**Comment by fieg** [comment]
This issue is closed because Infinite Ajax Scroll 2 [reached end of life](https://infiniteajaxscroll.com/blog/end-of-life-ias2/) and is being [superseded by v3](https://infiniteajaxscroll.com).

Suggestions given in this issue were taken into account when working on v3 and some are even implemented, see for e.g. https://infiniteajaxscroll.com/examples/masonry/. If you have questions, feedback or think this issue was closed by mistake, please comment on this issue.
