### ISSUE TITLE
load next page missing functionalitys [help]

### ISSUE THREAD

**Issue by davirs** [webcreate/infinite-ajax-scroll#239]
Hi. I'm newbie in javascript so need help and patience...
I already read http://infiniteajaxscroll.com/docs/events.html 

But I can´t rendered my hover funcion to display elements... 
Can you help-me debug theme function to rendered elements after  new results?

My script is:
```
window.ias.on('rendered', function(items) {
    var $items = $(items);
    $items.each(function() {
        $('.display-onhover', this).whatFuncionIsHere();
    });
})
```
_*whatFuncionIsHere = all functions that I tried not works.._

**First results page:
**![screenshot_26](https://cloud.githubusercontent.com/assets/4355062/14936856/2c92d03e-0ecd-11e6-8c45-0461ff86f6e3.png)

**News results page:
**![screenshot_27](https://cloud.githubusercontent.com/assets/4355062/14936858/3235636c-0ecd-11e6-847e-8d263c07ad25.png)

**## My demo with ultimotheme+infinite scroll** http://goo.gl/kcFfRZ

@fieg  Can you help me, please xD

**Comment by fieg** [comment]
You probably need to reinitialise your scripts. See: http://infiniteajaxscroll.com/docs/support.html#my-javascript-events-don-t-work-anymore-after-a-new-page-is-loaded
