### ISSUE TITLE
Next page link's href could be only static html path?

### ISSUE THREAD

**Issue by Farb** [webcreate/infinite-ajax-scroll#240]
I have seen the all examples on the site http://infiniteajaxscroll.com/examples/basic/page1.html,however,in my asp.net project,there is no html file.And I write the following code:
```html
<ul id="pagination">
    <li><a href="/MyOrder/ChargerBabyOrders/1"></a></li>
    <li class ="next"><a href="/MyOrder/ChargerBabyOrders/2"></a></li>
</ul>

```

The result is that '/MyOrder/ChargerBabyOrders/2' is requsted looply,'/MyOrder/ChargerBabyOrders/3' is never been requested!Why?Thanks in advance!

**Comment by Farb** [comment]
IAS support action url in the next page?Anyone can anwser me?

**Comment by fieg** [comment]
Please try the following:

* fix html  `class ="next"`
* try clicking the next link without IAS and see if it redirects correctly
* make sure there is only one element with the class next.
