### ISSUE TITLE
The site displays incorrectly in Mozilla Firefox

### ISSUE THREAD

**Issue by martybong** [webcreate/infinite-ajax-scroll#257]
http://infiniteajaxscroll.com/docs/getting-started.html

[27-08-2016 16-06-49](https://cloud.githubusercontent.com/assets/16646406/18027605/2cd6d2a0-6c71-11e6-9e07-7d7f4a137a67.png)

**Comment by martybong** [comment]
need **display: block;** for style **body.docs #main .article-wrapper .article pre code {display: block;}**

**Comment by fieg** [comment]
Thank you for your report. I will fix it asap.

**Comment by fieg** [comment]
Works in FireFox 53 on macOs.
