### ISSUE TITLE
ias not working and masonry from example

### ISSUE THREAD

**Issue by premiumwd** [webcreate/infinite-ajax-scroll#258]
Hi was wondering if you could help me. Here is the page

http://demo.premiumwd.com/themes/ellion/blog/

here is the code 

<code>
	 
	 if ($('.blog .content').hasClass('animated')){
		$('.blog .content').imagesLoaded( function() {
						
			 var masonryChild = $('.blog .content').find('article');
		 
			  masonryChild.each(function(i){
					setTimeout(function(){
						 masonryChild.eq(i).addClass('post-loaded animate');
					}, 200 * (i+1));
			  });
		 });
	 }	 
	 var items = $('.blog .content article');
	 items.each(function(){
		 $(this).css({
		 'height': $(this).height(),
		 'width': $(this).innerWidth()
		 }
		);
	 });
	 var container = document.querySelector('.blog .content');
    var msnry = new Masonry( container, {
      // options
      itemSelector: 'article',
      gutter: 10
    });

    var ias = $.ias({
      container: '.blog .content',
      item: "article",
      pagination: "#pagination",
      next: ".next a",
      delay: 1200
    });

    ias.on('render', function(items) {
      $(items).css({ opacity: 0 });
    });

    ias.on('rendered', function(items) {
      msnry.appended(items);
    });

    ias.extension(new IASSpinnerExtension({html: '<div class="loading-info littlepaddingbottom text-center" style="float:left;width:100%;"><i class="fa fa-refresh fa-spin fa-1x fa-fw"></i></div>'}));
    ias.extension(new IASNoneLeftExtension({html: '<div class="ias-noneleft" style="text-align:center"><p><em>You reached the end!</em></p></div>'}));

</code>

**Comment by fieg** [comment]
Did you found a solution?

**Comment by premiumwd** [comment]
yes
