### ISSUE TITLE
Not working on live server...

### ISSUE THREAD

**Issue by webtuts4u** [webcreate/infinite-ajax-scroll#260]
I am confused why its not working on live server. But working good in local server wp site. On live server plugin shown the spinner icon but not load the new items. Any guide line about this ?

Here's my js code:

``` javascript
jQuery(document).ready(function($) {
    var ias = $.ias({
        container: ".portfolio-list",
        item: ".pf-item",
        pagination: ".custom-pagination",
        next: ".custom-pagination .next",
    });
    ias.extension(new IASSpinnerExtension());
    ias.extension(new IASTriggerExtension({offset: 2}));
    ias.extension(new IASNoneLeftExtension({text: "No More Items Available."}));
});
```

**Comment by fieg** [comment]
This is probably to some misconfiguration when implementing IAS. Please visit http://infiniteajaxscroll.com/docs/ for documentation or you can ask you question on stackoverflow.

If you strongly believe this is due to a bug in Infinite AJAX Scroll, please comment on this issue with more details.
