### ISSUE TITLE
ias. is undefined

### ISSUE THREAD

**Issue by bulentcim** [webcreate/infinite-ajax-scroll#263]
I am using magento 1.9.0.1 on catalog search page, when loading the second page, i got error in Internet explorer 11.

The Url is : https://www.webzanem.com/gida-vitamin-takviyeleri-webzanem-fiyat-ucuz-indirim-kampanya-satin-al.html

My script at the footer of page is;

jQuery(function() {
   jQuery("img.lazy").lazyload();

});
window.onload = function () {
        ias.on('rendered', function() {
            jQuery("img.lazy").lazyload();
        })
}

and get an error "SCRIPT5009: 'ias' is undefined" 

Could you help for this?
Thanks

**Comment by fieg** [comment]
This is probably to some misconfiguration when implementing IAS. Please visit http://infiniteajaxscroll.com/docs/ for documentation or you can ask you question on stackoverflow.

If you strongly believe this is due to a bug in Infinite AJAX Scroll, please comment on this issue with more details.
