### ISSUE TITLE
How Do I integrate with Rails Kaminari Gem

### ISSUE THREAD

**Issue by nikhilgoyal** [webcreate/infinite-ajax-scroll#267]
The pagination is handled by the Kaminari

``` 
 def index
    @posts = Post.page(params[:page]).per(2)
  end
```

It will show two posts per load. Now the problem is when I keep on scrolling the `pagination` links keep on appending to the `container` after each load. 

When I change the above line to show just 1 post per load, it works fine. Where can I be going wrong with this or is this a bug.

**Comment by fieg** [comment]
Sorry I don't know Kaminari. Please try something like stackoverflow
