### ISSUE TITLE
Infinite ajax scroll did not working in Django

### ISSUE THREAD

**Issue by xiaowec** [webcreate/infinite-ajax-scroll#268]
I am trying to use this plugin into my Django projects. I followed the official tutorial and the code change is very straightforward. However it seems the Django project fails to find the jQuery.ias function. Here is the details:http://stackoverflow.com/questions/40582056/infinite-ajax-scroll-did-not-working-in-django

**Comment by fieg** [comment]
This is probably to some misconfiguration when implementing IAS. Please visit http://infiniteajaxscroll.com/docs/ for documentation or you can ask you question on stackoverflow.

If you strongly believe this is due to a bug in Infinite AJAX Scroll, please comment on this issue with more details.
