### ISSUE TITLE
Does the plugin remove DOM elements?

### ISSUE THREAD

**Issue by l2zeo** [webcreate/infinite-ajax-scroll#269]
I have a question on a big # of dom elmenets and performance.

Let's say I have 6000 dom elements on a page and the number of the elements can be increased as a user interact with the page (user scrolls to create a new dom element) like twitter.

Are they any other ways of improving a page with a lot of dom elements?

http://stackoverflow.com/questions/12613113/performance-with-infinite-scroll-or-a-lot-of-dom-elements

**Comment by fieg** [comment]
No, this plugin does not remove DOM elements. I'm closing this as this is a exact copy of the stackoverflow question, please continue there.
