### ISSUE TITLE
Problem with rows on WP masonry-style theme

### ISSUE THREAD

**Issue by olegi4sam** [webcreate/infinite-ajax-scroll#275]
Hi, have problem with rows on my site http://roza2012.net.ua with wp theme https://colorlib.com/wp/themes/pinbin/

I used code from here https://github.com/fieg/Infinite-Ajax-Scroll#integrating-with-jquery-masonry for integration, but it doesn't works well after loading next pages. 

![screenshot 2017-03-21 at 12 24 00](https://cloud.githubusercontent.com/assets/25985309/24143413/4a169676-0e32-11e7-8603-407f286a6be5.png)

I also tried code from http://infiniteajaxscroll.com/examples/masonry.html but also can't get good result.

Also if I scroll up, I see prob with grid elements that cover each other.

![screenshot 2017-03-21 at 12 31 43](https://cloud.githubusercontent.com/assets/25985309/24143493/88d3099e-0e32-11e7-9559-bb4c311d002c.png)

What can be solution for this wp theme? Thanks.

**Comment by fieg** [comment]
Hi olegi4sam, this is probably due to IAS/Masony not able to determine the correct height, as the images are not fully loaded yet. You can try to set a height on the image elements.

**Comment by fieg** [comment]
Hi, I did not hear from you anymore, therefor I'm closing this issue. If you think this issue is not resolved yet, please reopen.
