### ISSUE TITLE
ias auto load next page on invisible container

### ISSUE THREAD

**Issue by FAAAAT** [webcreate/infinite-ajax-scroll#279]
hello guys  
when i use the ias in a page that has 2 bootstrap tabs, ias in unactived tab will auto load the next page content when i first access the page.

how can i solve this problem?

i read the code behind , i think ias can judge the element's visibility. if not, then stop firing that event.

**Comment by FAAAAT** [comment]
var IASCallbacks = function (a) {
    return this.list = [],
    this.fireStack = [],
    this.isFiring = !1,
    this.isDisabled = !1,
    this.fire = function (a) {
        var b = a[0],
            c = a[1],
            d = a[2];
        this.isFiring = !0;
        //see the container visibility by lymi
        if (!$(b.itemsContainerSelector).is(':visible')) {
            c.reject();
        }
        for (var e = 0, f = this.list.length; f > e; e++) if (void 0 != this.list[e] && !1 === this.list[e].fn.apply(b, d)) {
            c.reject();
            break
        }
        this.isFiring = !1,
        c.resolve(),
        this.fireStack.length && this.fire(this.fireStack.shift())
    },
    this.inList = function (a, b) {
        b = b || 0;
        for (var c = b, d = this.list.length; d > c; c++) if (this.list[c].fn === a || a.guid && this.list[c].fn.guid && a.guid === this.list[c].fn.guid) return c;
        return -1
    },
    this
};

change the define to this will resolve this problem

**Comment by fieg** [comment]
Hi FAAAAT, thank you for your proposed code change. I will look into it when I get the time. IAS should definitely not interfere between separate containers.

**Comment by fieg** [comment]
I misread your issue before, but what you want can be achieved with this change: #305. You can set the `initialize` option to `false` and call [initialize](https://infiniteajaxscroll.com/docs/methods.html#initialize) when the tab becomes visible.
