### ISSUE TITLE
Retaining previous pages when returning to paginated view using the History Extension.

### ISSUE THREAD

**Issue by rasmniel** [webcreate/infinite-ajax-scroll#280]
I didn't think to post the issue here initially, so I made one on StackOverflow.

If you don't mind a reference, here it is: 
http://stackoverflow.com/questions/44050301
Otherwise, let me know and I will rephrase the issue here.

Thanks in advance for any help you can provide!

**Comment by fieg** [comment]
I believe you are requesting something similar to #274, am I correct?

**Comment by rasmniel** [comment]
Yes, that is correct!

**Comment by fieg** [comment]
Ok, I'll close this in favor of #274 then.
