### ISSUE TITLE
issue with pop-up

### ISSUE THREAD

**Issue by shanka12** [webcreate/infinite-ajax-scroll#288]
I am trying to use infinite scroll on pop-up. fixed-height pop-up with scroll bar. when I scroll down data not loading. when I scroll down main page scroll bar, data loading on pop-up.
Any solution for this?

**Comment by fieg** [comment]
Hi there! I think what you are looking for it the overflow method, like demo'd here: https://infiniteajaxscroll.com/examples/overflow.html

Start with adding a div in the popup and give it an id, for example `overflow`. Then initialize IAS with something like:

```js
var ias = $('#overflow').ias({
  container:  ".container",
  item:       ".item",
  pagination: "#pagination",
  next:       "a.next",
});
```

Make sure the content in the overflow div contains the right elements (`.container`, `.item`, etc.).

**Comment by shanka12** [comment]
Thank you
