### ISSUE TITLE
Searching for license examples (COMMERCIAL and UNLIMITED)

### ISSUE THREAD

**Issue by rjgamer** [webcreate/infinite-ajax-scroll#293]
@fieg I'm the creator of a software which is licensed under GPL v3. But now I want to sell the software for "commercial use" like Infinite Ajax Scroll. 

I'm a real noob in licensing. So my question: Can you send me an example of your license-text (COMMERCIAL and UNLIMITED) so I can customize it?

Thanks a lot!

**Comment by fieg** [comment]
Hi Jonathan. If you contact me at jeroen a t webcreate nl we can work something out.
