### ISSUE TITLE
Uncaught ReferenceError: IASSpinnerExtension is not defined

### ISSUE THREAD

**Issue by marconett** [webcreate/infinite-ajax-scroll#294]
Using the minified version from the website (2.2.3) and the following js, I'm getting said error. 

```
 var ias = $.ias({
    container:  "#my-item-container",
    item:       ".my-item",
    pagination: "#pagination",
    next:       ".next"
  });

  ias.extension(new IASSpinnerExtension());
```

**Comment by marconett** [comment]
I can work around this by removing the `var` from the `IASSpinnerExtension` definition and thereby making it avaliable globally: https://github.com/webcreate/infinite-ajax-scroll/blob/master/src/extension/paging.js#L11

**Comment by fieg** [comment]
Thank you for your report. I will look into it later today when I get home. 

Can you in the mean time make a minimal setup in something like codepen.io to reproduce this? And can you provide your jQuery version and browser vendor+version? Thanks a lot!

**Comment by marconett** [comment]
I'm using jQuery 1.12.4.

Can't reproduce this with a simple setup: https://codepen.io/anon/pen/Mozvez?editors=1010#0

In my project, I'm using webpacks require to include file like so: `require('./jquery-ias.min');`. That setup is not reflected in the codepen.

**Comment by fieg** [comment]
Ok, I looked into it. I've found the following solution:

Install webpack's script-loader

```
npm install --save-dev script-loader
```

then require IAS like this:

```
require('script-loader!../vendor/jquery-ias.min');
```

I understand this is far from ideal and I will look, later on, if I can make IAS work better with webpack. But for now this should work.

**Comment by marconett** [comment]
Thank you for your help. Will try that when I find some time, but for now I'm good with the my solution of just making the function globally available :)

You can close the ticket if you want to.

**Comment by alexeyMohnatkin** [comment]
`require('script-loader!../vendor/jquery-ias.min');`
I still get this error: `Uncaught ReferenceError: IASSpinnerExtension is not defined`

**Comment by fieg** [comment]
Ah, yes IAS exposes a few global variables. Are you requiring in a global context?
