### ISSUE TITLE
Infinite scrolling with only one item

### ISSUE THREAD

**Issue by mheiduk** [webcreate/infinite-ajax-scroll#296]
Hi,

thanks for the great plugin, works great so far with my masonry grid!

At the moment I am trying to implement a solution where, on an articles page, another article gets loaded when the user reaches the end of the site. The plugin works, but loads another article for every pixel I scroll. I think the problem is, that there is only one item, which is in the viewport and then the plugin gets triggered.

Is there any workaround where I can solve this issue? Best case would be that the plugin gets triggered only at the end of the item.

Thanks in advance!

Best,
Marc

**Comment by fieg** [comment]
Hi Marc, thank you for your report. Can you provide a minimal test case? I have implemented this with single articles before, but did not have this issue.

**Comment by mheiduk** [comment]
Thanks for the fast reply! I've uploaded the site under this url temporarily: http://skatze.monopol.org/

It occurs on every article page. However the masonry grid on the front page works great. Would be great if you can help!

Best,
Marc

**Comment by fieg** [comment]
Hi, I looked at your site, but unfortunally I could not find the problem. There is a lot going on, jacascript-wise. There could be a conflict with some other script. Can you try to reduce complexity and debug from there? I would love to have another look then.

**Comment by mheiduk** [comment]
Yeah, there is a little bit going on with js, some included in the ready-to-use Wordpress theme. I'll try to exclude the js temporarily in the week after next week and I'll inform you, if I can find the conflict.

Thanks for your help!

**Comment by mheiduk** [comment]
Finally I've found the issue, the item option was assigned to an absolute positioned element. Block elements just work fine.

Best,
Marc
