### ISSUE TITLE
How do I use the updated versions of Masonry + Infinite Scroll on a design?

### ISSUE THREAD

**Issue by juliamcorrea** [webcreate/infinite-ajax-scroll#297]
So I'm fairly experienced at HTML and CSS because I've been morphing the same code over and over again in order to create new designs, never changing the JavaScript plug-ins. But I decided it's about time to step up my game and now I'm starting to learn JavaScript as well. Upon analyzing my designs, I noticed that my version of Infinite Scroll has been extremely outdated (v.2.2) and I decided that it's about time that I start updating my codes, so I visited the Infinite Scroll website and got some codes, like this one:
`<script src="https://unpkg.com/infinite-scroll@3/dist/infinite-scroll.pkgd.min.js"></script>`
Not only it stopped working, but also ruined the structure of the multiple-column design. I found that Masonry was supposed to help with getting it back together, so I got me some Masonry coding as well and placed both codes before _</head>_:
`<script src="https://unpkg.com/masonry-layout@4/dist/masonry.pkgd.min.js"></script>`
And finally, I added some JavaScript to the end of the page:
```{block:IndexPage}
<script type="text/javascript">
// init Masonry
var msnry = new Masonry( '.grid', {
});
// init Infinite Scroll
var infScroll = new InfiniteScroll( '.grid', {
  // Infinite Scroll options...
  append: '.grid__item',
  outlayer: msnry,
  navSelector    : '#pagination',  
  nextSelector   : '#pagination a#nextPage',
  itemSelector: '.grid__item', 
  bufferPx : 40,
});
infScroll.loadNextPage();
</script>
{/block:IndexPage}
```
Masonry is working fine, which I'm pretty proud about, but my Infinite Scroll still doesn't work. I'm desperate, lost, confused and upset. Can someone please help me?
In case you're curious or wandering about how I managed to screw up, [here is the preview](https://juliacmcorrea.tumblr.com/), [here is the full code of the screwed up theme](https://pastebin.com/FFx5V95k), and [here is a link to the code that was using before](https://pastebin.com/KifvneEy).

**Comment by fieg** [comment]
You posted to the wrong repo. This one is for [Infinite Ajax Scroll](https://infiniteajaxscroll.com).
