### ISSUE TITLE
Uncaught Error: Syntax error, unrecognized expression: <!DOCTYPE HTML> when has space before <!DOCTYPE HTML> 

### ISSUE THREAD

**Issue by RockNHawk** [webcreate/infinite-ajax-scroll#302]
If the AJAX response have some space before the HTML start tag <!DOCTYPE HTML>
jQuery will throw this error.
Emmmmmmm..., I found two way to fix it, make sure server response  `<!DOCTYPE HTML>` as response first start string,
or plugin trim the response string before call 
`e = $(this.itemsContainerSelector, b.trim()).eq(0)`

I think plugin should trim the html code , or display a waring in console.

**Comment by fieg** [comment]
Thank you for your report. I don't want to bloat the plugin with fixes for everything that can go wrong with a website, but I will take it into consideration.

**Comment by darklx** [comment]
@fieg I agree with you, without any notice, developer will puzzled, Such as one ajax page is OK, but another ajax page failed, I taked many time to find this reason.

**Comment by fieg** [comment]
Lol, I totally forgot about this, but look what I found: https://infiniteajaxscroll.com/docs/support.html#uncaught-error-syntax-error-unrecognized-expression

**Comment by fieg** [comment]
I'm closing this issue because Infinite Ajax Scroll 2 [reached end of life](https://infiniteajaxscroll.com/blog/end-of-life-ias2/) and is being [superseded by v3](https://infiniteajaxscroll.com).

If you have questions, feedback or think this issue was closed by mistake, please comment on this issue.
