### ISSUE TITLE
?ajax=1 being pushed instead of next page url

### ISSUE THREAD

**Issue by iantearle** [webcreate/infinite-ajax-scroll#303]
Have this working on a live implementation of a website, but on my dev machine where I am using Slim Framework to update the backend i'm getting "?ajax=1" in the url after the second page loading. 

So everything is fine on loading page two, but page three will get "?ajax=1/page/3" then four will get "?ajax=1?ajax=1/page/4" and i Have no idea why?

Can you help?

**Comment by fieg** [comment]
Hi, I need some more informatie to be able to help you. Can you make a minimal use case where the issue occurs, so I can have a look at it?

**Comment by fieg** [comment]
Infinite Ajax Scroll does not append parameters to url unless you tell it to (see for example https://infiniteajaxscroll.com/docs/events.html#load).
