### ISSUE TITLE
No FadeIn for new posts

### ISSUE THREAD

**Issue by happynautpro** [webcreate/infinite-ajax-scroll#312]
Hi Guys,

very good scroll widget. Is is possible the show the new loaded items directly, without the short fading effect?

Thanks in advance.

**Comment by fieg** [comment]
Hi, good question. This should be possible by rendering the items yourself. 

You can try the following:

```
ias.on('render', function(items) {    
  this.getLastItem().after(items);

  this.fire('rendered', [items]);

  return false;
}, -1);
```

Example: https://jsfiddle.net/nryg1r46/22/
