### ISSUE TITLE
Back Button Position

### ISSUE THREAD

**Issue by reziprok** [webcreate/infinite-ajax-scroll#314]
Right now the trigger and history extension loads new pages by scrolling to the negativeMargin value ov the viewport in respect of the scroll container. The Problem is that the url gets updated with replaceState too early. In my eyes ist should switch to /page/2/ when the first article of page2 is on top of the vierwport. Cause right now when I click on the last article on /page/1/ the url is already updated to /page/2/, resulting in wrong page beeing loaded onBack. So a later update onScroll of the url would fix that problem. 
Anybody has a solution for this? Would be veeeery glad for help :-)

**Comment by fieg** [comment]
If it should switch at the bottom of the viewport of on the top of the viewport is an opinion. Currently it switches when the next page scrolls into view from the bottom of the viewport. Nevertheless I understand what you want and think this should be configurable. 

This is something I will work on in [version 3 of ias](https://v3.infiniteajaxscroll.com).

**Comment by fieg** [comment]
While working on other issues I have now got a clearer picture of what is wanted here. The negativeMargin should be decoupled from the actual pageChange, as stated here: https://github.com/webcreate/infinite-ajax-scroll/issues/428#issuecomment-570786424

Work will continue in the linked issues therefor I'm closing this issue.
