### ISSUE TITLE
Next items inserting after First Items on page.

### ISSUE THREAD

**Issue by leovalitov** [webcreate/infinite-ajax-scroll#315]
Hello!
I faced a similar situation
In the debugging process, I found that the function GetLastItem works incorrectly
I tried to solve the problem as follows
`

    this.getLastItem = function() {
            var a1=this.itemSelector;
            var a2=this.getItemsContainer();
            var a3=this.getItemsContainer().get(0);
            var a31=this.getItemsContainer().children();
            var a32=this.getItemsContainer().children().filter(this.itemSelector);
            var a33=this.getItemsContainer().children().filter(this.itemSelector).last();
            return a33;

            var a40=$(this.itemSelector, a2);
            var a41=$(this.itemSelector, this.getItemsContainer());
            var a42=$(this.itemSelector, this.getItemsContainer().eq(0));
            var a43=$(this.itemSelector, this.$container);
            var a4=$(this.itemSelector, this.getItemsContainer().get(0));
            var a5=$(this.itemSelector, this.getItemsContainer().get(0)).last()

      return $(this.itemSelector, this.getItemsContainer().get(0)).last();
    };
`

Perhaps you need it to improve your plugin

**Comment by fieg** [comment]
Closing due to no response.
