### ISSUE TITLE
Question about licence

### ISSUE THREAD

**Issue by ihor-sviziev** [webcreate/infinite-ajax-scroll#319]
Hi,

I'd like to install magento 2 module that currently bundling jquery-ias plugin. In head contains information that for commercial use we need to buy license:
https://github.com/Strategery-Inc/Magento2-InfiniteScroll/blob/master/view/frontend/web/js/jquery-ias.min.js#L6

Could you explain, should we buy license for using this extension on Magento 2 in commercial projects?

**Comment by fieg** [comment]
Hi, thanks for reaching out. The short answer is:

Yes, you need a commercial license.

I will try to elaborate on this specific plugin later when I have some more time.
