### ISSUE TITLE
IAS 3: Feature list

### ISSUE THREAD

**Issue by mheiduk** [webcreate/infinite-ajax-scroll#327]
Hi,
thanks for developing a new version of IAS. I use IAS 2 in several projects with a commercial license and I am very interested in v3.

In the new documentation I am missing some features which are present in IAS 2, for example the number of pages which load automatically. I assume that some additional features are going to be added over time. Is there a list which features are planned for the final version of IAS 3?

At the moment I am missing these features:
- Trigger Extension: load previous items, offset
- Options: negative margin

Thanks!

Best,
Marc

**Comment by fieg** [comment]
Hi Marc,
Thanks for checking out IAS3! Yes, you are correct, some features are still being worked on and will be ready before the final launch. A list/roadmap for coming features is a great idea. I will see if I can put something up. 
ps. Can you reach out to me by email (reply to private beta mail)? I would love to hear more about your projects and use cases.

**Comment by fieg** [comment]
Hi @mheiduk, For your interest: These features have landed in [v3.0.0-beta.6](https://github.com/webcreate/infinite-ajax-scroll/releases/tag/v3.0.0-beta.6)

**Comment by mheiduk** [comment]
Hi @fieg, thanks for the info. Currently I am not working with Infinite Scroll, but I'll check it out anyways :)
