### ISSUE TITLE
Invoice issue

### ISSUE THREAD

**Issue by Nuranto** [webcreate/infinite-ajax-scroll#329]
Sorry, I didn't found any email or contact form anywhere, so I post here...

I bought a license, and needed an invoice for accounting :) I downloaded from gumroad, but amount is not correct (29€ instead of 29.14€ debited)...

I think I will survive, but... it's just to let you know...

**Comment by fieg** [comment]
Hi @Nuranto, thanks for letting me know. Gumroad doesn't provide much insight here on my side, but could it be that it are exchange/transaction costs from your credit card provider?
