### ISSUE TITLE
Question about new version (V3)

### ISSUE THREAD

**Issue by happynautpro** [webcreate/infinite-ajax-scroll#331]
Hi :)

When will IAS version 3 be available?

**Comment by fieg** [comment]
Hey 👋 

It's currently in private beta, but release is scheduled for later this year. Can't promise any dates yet. If you want to try out the beta, you can sign up at https://v3.infiniteajaxscroll.com/

**Comment by fieg** [comment]
Hi @happynautpro,
Just wanted to let you know I moved v3 to public beta, so you can try it if you like.

Examples: https://v3.infiniteajaxscroll.com/examples/
Docs: https://docs.v3.infiniteajaxscroll.com/
