### ISSUE TITLE
[Question] Need assistance - Getting started

### ISSUE THREAD

**Issue by Lakhiii** [webcreate/infinite-ajax-scroll#348]
Do you have samples projects online that i can use as reference?

I am trying to do the basic examples in https://infiniteajaxscroll.com/

but the infinite scroll is not working. 

I was hoping to see some sample projects for me to move forward Thanks!

**Comment by fieg** [comment]
I have some examples for the upcoming v3 version (currently in beta):
https://v3.infiniteajaxscroll.com/examples/

You can find documentation for it here:
https://docs.v3.infiniteajaxscroll.com/

**Comment by Lakhiii** [comment]
Thanks very much the v3 looks more fluid and beautiful. Can't wait to use it. 

How about a sample for v2? like a code fiddle? because i was wondering how IASNoneLeftExtension works and how does it determine that no more elements left? in my sample project, i added 2 pages under the pagination with a next class but shows no more elements left..

Another thing, the other pages content, should it have the container and element set again in the html?

**Comment by Lakhiii** [comment]
Hello Saw that mine is similar with this issue. 
https://github.com/webcreate/infinite-ajax-scroll/issues/318

I'll try first and comment here for my update. thanks!

**Comment by Lakhiii** [comment]
Hello Tried a different approach and was able to make it work. 

I mimic the first page content with the other pages and IAS worked..

In my controller, i made some pagination management. Thanks everyone for the help!

**Comment by fieg** [comment]
Glad to hear you worked it out 👍
