### ISSUE TITLE
Error "Uncaught (in promise) XMLHttpRequest"

### ISSUE THREAD

**Issue by webkubikc** [webcreate/infinite-ajax-scroll#349]
Hello. I used earlier the second version of your plugin, today I decided to try 3, but faced with such a problem, the plugin refuses to work. When you scroll in the console gives the following. The second version of the plugin works. I work on a local server - OpenServer

GET http://yammystream.com/undefined?1563237713529 404 (Not Found)
libs.js:335 Request failed
(index):1 Uncaught (in promise) XMLHttpRequest {onreadystatechange: ƒ, readyState: 4, timeout: 0, withCredentials: false, upload: XMLHttpRequestUpload, …}

**Comment by fieg** [comment]
Thanks for trying v3. Can you make a reduced test case or provide a live url? Otherwise I can't debug the issue.
