### ISSUE TITLE
Infinite scroll in tab navigation problem

### ISSUE THREAD

**Issue by DariuszPowroznik** [webcreate/infinite-ajax-scroll#354]
Hi,
I'm trying to use your infinite-ajax-scroll (v3) on page where I have tab navigation (from Bootstrap v4). In one tab I have articles and in second I have products. 
In both I wanted to have infinity scroll working independent.

I was trying to working with bind/unbind but it's not working. This is how I tried to use it:

```
       var art = new InfiniteAjaxScroll('#Articles', {
            item: '.Article',
            next: '.nextArt',
            pagination: '#ArticlePagination',
            spinner: '.Artspinner'
        });

        var prod = new InfiniteAjaxScroll('#Products', {
            item: '.InfiniteProduct',
            next: '.nextProduct',
            pagination: '#ProductPagination',
            spinner: '.Prodspinner',
            bind: false
        });

        $('#tab-newsSearch').on('click', function (e) {
            e.preventDefault();
            prod.unbind();
            setTimeout(function () { art.bind(); }, 100);
        })

        $('#tab-productsSearch').on('click', function (e) {
            e.preventDefault();
            art.unbind();
            setTimeout(function () { prod.bind();  }, 100);
        })
```

Is there any posibility yo use it that way?

**Comment by fieg** [comment]
Do you happen to see any errors or warnings in the developer console?

**Comment by DariuszPowroznik** [comment]
Nope - no errors. When I switch to next tab it just run all events at once and stop working.

**Comment by fieg** [comment]
Ok, well I think this current beta release doesn't support it quite yet - it will be in the final 3.0 release tho. I have to work some more on it, but I can't promise any dates.

**Comment by fieg** [comment]
Hi Dariusz, Looking at your issue again.. What I'm missing is the [scrollContainer](https://docs.v3.infiniteajaxscroll.com/options#scrollcontainer) option. Can you try adding that?

**Comment by fieg** [comment]
@DariuszPowroznik any luck with the scrollContainer option?

**Comment by fieg** [comment]
Rel #369

**Comment by DariuszPowroznik** [comment]
Hi,
I didn't try it because I used standard pagination. Maybe in next project I will try to use it again and I will let you know if it's working.

**Comment by fieg** [comment]
FYI: I released a new version which solved an issue with multiple instances. 

An demo is available here: https://infiniteajaxscroll.com/examples/overflow/
