### ISSUE TITLE
Write text when this script got a last page

### ISSUE THREAD

**Issue by XIOLog** [webcreate/infinite-ajax-scroll#357]
Hello.

How can I write text below products when this script got a last page? I can`t find it in documentation :-(

**Comment by fieg** [comment]
What version of IAS are you referring to?

**Comment by XIOLog** [comment]
3

**Comment by fieg** [comment]
Great. I have an example available here:
https://codesandbox.io/s/github/webcreate/infinite-ajax-scroll/tree/master/examples/articles

You will see an html element with the class "no-more". This element is hidden with css by default.
Next we listen to the "last" event and show the element:

```
ias.on('last', function() {
  let el = document.querySelector('.no-more');

  el.style.opacity = '1';
});
```

Let me know if this works out for you.

**Comment by XIOLog** [comment]
This work for me. Thank you :-)

One more question.

I have categories. How can I send category ID to script? I want to select products which contains in that category.

**Comment by fieg** [comment]
Glad it worked!

I guess we are continuing your second question in #362 😄
