### ISSUE TITLE
<script> tags are removed after items loaded

### ISSUE THREAD

**Issue by adarshkhatri** [webcreate/infinite-ajax-scroll#373]
**Support question**

After ajax call, content is loaded but my `<script>` tags are removed. Is there a way to keep them? My script depends on each item.

**Environment**
I am using this script in my Magento site to load category infinitely.

- Infinite Ajax Scroll version:
- Browser version: 1.0.2
- Operating System: Windows?

**Comment by fieg** [comment]
This is not supported out of the box, but might be added using custom event listeners.

Are you using IAS v2 or v3?

**Comment by adarshkhatri** [comment]
> *!
>  * Infinite Ajax Scroll, a jQuery plugin
>  * Version 1.0.2
>  * https://github.com/webcreate/infinite-ajax-scroll
>  *
>  * Copyright (c) 2011-2013 Jeroen Fiege
>  * Licensed under MIT:
>  * https://raw.github.com/webcreate/infinite-ajax-scroll/master/MIT-LICENSE.txt
>  */

Any examples on event listeners?

**Comment by fieg** [comment]
Hmm, v1, that's no longer supported and I don't think it's possible in that version. 
I advise you to upgrade to v3.
