### ISSUE TITLE
Load All Remaining Pages

### ISSUE THREAD

**Issue by lear2000** [webcreate/infinite-ajax-scroll#386]
Possible to load all remaining pages after
ias.on('loaded', function(data, items) {}

IE:
ias.on('loaded', function(data, items) {

LOAD REMAINING ITEMS 

}

I have tried offset but it repeats
I tried next, but i am not sure if i can say get total # of pages then load X remaining pages using next

I have also tried setting the margin to 999999 but that does not work either

**Comment by fieg** [comment]
What version are you using? v2 or v3?

**Comment by lear2000** [comment]
Version 2

> On Oct 26, 2019, at 8:58 AM, Jeroen Fiege <notifications@github.com> wrote:
> 

﻿
What version are you using? v2 or v3?

**Comment by fieg** [comment]
Only way to keep loading is to keep calling `next`. There is no way to get the total number of pages from IAS, but you could inject this yourself.
