### ISSUE TITLE
How can I `reinitialize` on V3? 

### ISSUE THREAD

**Issue by ivanasetiawan** [webcreate/infinite-ajax-scroll#396]
**Support question**

I have been trying to google around but with no succes! there's also no `destroy`? 
How can I `reinit` IAS on V3? (no jquery, I am using `import InfiniteAjaxScroll from '@webcreate/infinite-ajax-scroll';`)

- Infinite Ajax Scroll version: 3
- Browser version: FF Dev 71.0b5 (64-bit)
- Operating System: OS Catalina (10.15.1)

**Comment by fieg** [comment]
My answer from https://stackoverflow.com/questions/58790605/how-can-i-reinitialize-or-destroy-infiniteajaxscroll-v3:

You can call [`unbind`](https://docs.v3.infiniteajaxscroll.com/reference/methods#unbind) to remove all event listeners. This should be enough to "destroy" IAS.

Otherwise you can probably overwrite the variable that contains the IAS instance.

Pseudo code example:

```js
// previous instance
var ias = InfiniteAjaxScroll(/* options */);

// destroy
ias = null

// reinitialize
ias = InfiniteAjaxScroll(/* some other options */);
```

**Comment by ivanasetiawan** [comment]
Hi @fieg! Thanks for answering! I tried both `unbind` and also `ias = null` but the URL still loading the old state. Case:
1. load ias page 2 & 3
2. trigger filtering with `select` element (`AJAX GET` on `change`)
3. I scroll down and see the old state as if I am scrolling on the old state:
`Start loading http://abc.com:8000/browse/?page=2&1573468431687&page=3&1573468434722&page=4`

**Comment by fieg** [comment]
Can you check if your pagination links are correct, because this looks strange: `?page=2&1573468431687&page=3&1573468434722&page=4`. The `page` argument is appended, instead of replaced.

**Comment by ivanasetiawan** [comment]
Hi @fieg! Yea it currently works like that, I previously used the `jquery-ias v2.2.3` and it worked perfectly (also with `$.ias().reinitialize();`)

Is there a way for me to install this version instead of using `import InfiniteAjaxScroll from '@webcreate/infinite-ajax-scroll';`?

**Comment by fieg** [comment]
I didnt see this behavior with other implementations, so I guess it something specifics in yours. Do you have a live url so I can check it out?

**Comment by fieg** [comment]
@ivanasetiawan I released a new beta version which fixes an scoping issue. Maybe that caused to old url to persist. Can you try the new version and see if it fixes your problem?

**Comment by ivanasetiawan** [comment]
@fieg Awesome! I will update and let you know

**Comment by fieg** [comment]
I think like this:

```
// previous instance
var ias = InfiniteAjaxScroll(/* options */);

// destroy (not really needed)
ias = null

// reinitialize (creates new instance)
ias = InfiniteAjaxScroll(/* some other options */);
```

**Comment by fieg** [comment]
I’m closing this issue for now. Please let me know if it works as suggested. If it doesn’t you may reopen the issue.

**Comment by ivanasetiawan** [comment]
@fieg apology for the delay! It seems to be working properly. Thank you!

**Comment by fieg** [comment]
Np, glad to hear it's working!
