### ISSUE TITLE
Multi instance in one page still have an issue after researching a lot.

### ISSUE THREAD

**Issue by TejasGajjar** [webcreate/infinite-ajax-scroll#403]
Can it be possible to have multiple instances on the same page with different overflow. The problem appears if you initialize the infinite ajax scroll in your main javascript file which will be loaded on every page, then the first initialization will be overwritten.

**Comment by fieg** [comment]
This should be possible, but there currently is an issue with multi instance support. Can you try the proposed fix from #369 and let me know if that fixes it for you?

**Comment by fieg** [comment]
I've release a new version which fixes an issue with multiple instances. 

You can see an example here: https://infiniteajaxscroll.com/examples/overflow/

I'm closing this for now. If you think the issue still persists, feel free to reopen this issue.
