### ISSUE TITLE
Expected single element for "pagination.element"

### ISSUE THREAD

**Issue by Nuranto** [webcreate/infinite-ajax-scroll#423]
V3-beta5

If we have two pager (one on top, on on bottom), we get this error :

``` 
Expected single element for "pagination.element"
```

**Comment by fieg** [comment]
Hi Nuranto, thanks for reporting this. It's an interesting use case and I think you are right that it is a bug. I can't think of a reason to limit this option to a single element.

**Comment by Nuranto** [comment]
The error is gone which is good !
However, only one of the two pager is hidden (the second one, at the bottom is still visible)

**Comment by fieg** [comment]
Ok, I see the problem. I will fix it.

**Comment by fieg** [comment]
This landed in [v3.0.0-beta.6](https://github.com/webcreate/infinite-ajax-scroll/releases/tag/v3.0.0-beta.6) which was released earlier today.
