### ISSUE TITLE
negativeMargin option in V3 ?

### ISSUE THREAD

**Issue by Nuranto** [webcreate/infinite-ajax-scroll#428]
In V3, the option "negativeMargin" has disappeared. We were using it in V2, and we miss it on V3 ?
Is there a reason ? Or is it just some oversight ?

**Comment by fieg** [comment]
Yes, I haven't implemented it yet. I was overthinking it's usefulness, so I'm glad to hear your actually need it. Can you tell me a bit why you precisely need it? If you could somehow show your use case to me it would be even better.

**Comment by Nuranto** [comment]
Well, I just want the users to wait the less as possible. So, ideally, the user don't see the loader most of the time. To do that, the negative margin can do the trick.
It is for a list of products on an ecommerce, and the idea is to load the next page when the user have 1 or  two lines of products left before seeing the end of the page.

**Comment by fieg** [comment]
Ok, I understand. I've added this feature to my backlog. Can't promise a delivery date tho.

**Comment by fieg** [comment]
I will take this suggestion from #238 into account when working on this feature

> What would be useful is a new option to declare the scroll offset to render the next page, which is decoupled from the scroll offset setting that triggers the "pageChange" event.

**Comment by fieg** [comment]
This feature landed in master. Could try it out and let me know if it works for you @Nuranto ?

**Comment by Nuranto** [comment]
@fieg Sorry, How can I generate the dist files ?

**Comment by fieg** [comment]
I wrote some instruction on how to generate dist files locally:
https://github.com/webcreate/infinite-ajax-scroll/blob/master/CONTRIBUTING.md#generating-dist-files-from-source

Please let me know if this works for you.

**Comment by Nuranto** [comment]
Thanks.
After some tests, it seems to work like a charm. 
I spotted another issue however, but I'll update the accurate issue (#423)

**Comment by fieg** [comment]
Thank you for testing. It will land in 3.0.0-beta.6 soon.

**Comment by fieg** [comment]
This landed in [v3.0.0-beta.6](https://github.com/webcreate/infinite-ajax-scroll/releases/tag/v3.0.0-beta.6) which was released earlier today.
