### ISSUE TITLE
Error if one page and no pager

### ISSUE THREAD

**Issue by Nuranto** [webcreate/infinite-ajax-scroll#443]
``` Uncaught Error: Element ".pages ol" not found for "pagination.element"```

If there is one page only, some framework may not show at all the pages links. That case should be errorless. (even if we will agree, the best would be to instantiate IAS only if there is more than one page)

**Comment by fieg** [comment]
Yes, I think it might be better to throw a warning instead of an Error.

**Comment by fieg** [comment]
This landed in [v3.0.0-beta](https://github.com/webcreate/infinite-ajax-scroll/releases/tag/v3.0.0-beta.6) which was released earlier today.
