### ISSUE TITLE
Last is not working for me

### ISSUE THREAD

**Issue by TheRealArtonn** [webcreate/infinite-ajax-scroll#461]
So I am using infinite ajax scroll on my gallery, it is basically a list of blogs ordered in a grid of 3 x 9. All these blogs are extracted from my database with msqli, here I am using LIMIT and OFFSET to make that possible. So far it works fine I can use the trigger function to show the next batch of my rows from the database, but I suspect my way of doing this might not make the last function probably?

this is my jquary

```
let ias = new InfiniteAjaxScroll('.content__row', {
    item: '.map',
    next: '.next',
    pagination: '.pagination',

  trigger: '.trigger'
});

ias.on('last', function() {
  let el = document.querySelector('.no-more');

  el.style.opacity = '1';
})
    
ias.on('pagenumber', (e) => {
    document.title = e.title;

    let state = history.state;

    history.replaceState(state, e.title, e.url);
});
```

**Comment by fieg** [comment]
To make the [last event](https://docs.infiniteajaxscroll.com/reference/events#last) work make sure the last page doesn't have the `.next` element.

**Comment by fieg** [comment]
Also "pagenumber" is not a valid event, this should be "page"

```
// wrong
ias.on('pagenumber', (e) => {

// correct
ias.on('page', (e) => {
```

**Comment by TheRealArtonn** [comment]
Does the event page react on a value from the url? for an example  "example.com&page=1"

**Comment by fieg** [comment]
Yes
