### ISSUE TITLE
Uncaught SyntaxError: Identifier 'ias' has already been declared

### ISSUE THREAD

**Issue by TheRealArtonn** [webcreate/infinite-ajax-scroll#462]
I am trying to make an additional infinity scroll as my webpage has two forms of grids for my gallery, basicially one with a grid 3x9 and another where it basically rows with more information.

since one of the containers is named container__grid and the other is named container__row I thought that duplicating the 

```
let ias = new InfiniteAjaxScroll('.content__row', {
    item: '.map',
    next: '.next',
    pagination: '.pagination',

  trigger: '.trigger'
});
```
would allow me to make it work like I wanted but instead I am getting this error

`Uncaught SyntaxError: Identifier 'ias' has already been declared`

**Comment by fieg** [comment]
JavaScript doesn't allow to use let on the same variable twice. You can use different variable names:

`let ias1 = new InfiniteAjaxScroll(...)` 
`let ias2 = new InfiniteAjaxScroll(...)`
