### ISSUE TITLE
Already a pagination to use it?

### ISSUE THREAD

**Issue by dd2424** [webcreate/infinite-ajax-scroll#497]
Hello, just a question please,
you must already have a Pagination to use it?
Thank you.

**Comment by fieg** [comment]
Not necessarily, you can go without Pagination if you want to load from JSON for example.

**Comment by dd2424** [comment]
hi
I have no pagination. I don't have JSON. I have items generated by a search form in GET method.
Can I use your infinite-ajax-scroll?
thanks

**Comment by fieg** [comment]
Yes you can. Be sure to try it out before you buy a license.

**Comment by dd2424** [comment]
Site Web, doc : 

> Infinite Ajax Scroll is a javascript infinite scrolling plugin. It works by reading the next (and previous) links of your existing server-side pagination and load these pages via AJAX when the visitor scrolls to the end of the page.

You must already have pagination on the server side, otherwise it does not work.
[https://docs.infiniteajaxscroll.com/#what-is-infinite-ajax-scroll](https://docs.infiniteajaxscroll.com/#what-is-infinite-ajax-scroll)

**Comment by fieg** [comment]
Have a look at these examples:
- https://infiniteajaxscroll.com/examples/blocks/
- https://infiniteajaxscroll.com/examples/json/

These don't have server-side pagination. You do need some JavaScript skills, but these examples should give you a head start.

**Comment by dd2424** [comment]
ok I understood :)
but .. the googlebot deactivate JavaScript, then you need pagination on the server side + html. that's right ?
thanks

**Comment by fieg** [comment]
Google is better at indexing javascript sites these days, so it might not be necessary. I still think it's best practice to have server-side pagination.
