### ISSUE TITLE
Is there any way to make this work with dynamic content like pjax or htmx

### ISSUE THREAD

**Issue by JeansouLiu** [webcreate/infinite-ajax-scroll#520]
**Support question**

Live version: https://class13.jeansou.com/record
This page uses htmx.js to make dynamic load, but ias seems not work well with it. When entering a page and returning to article list, ias will not work. 

**Environment**

- Infinite Ajax Scroll version: 3.0.0-beta.6
- Browser version: Microsoft Edge 83.0.478.56  (64 bit)
- Operating System: Windows 10 OS Version 2004 (Build 19041.329)

**Comment by fieg** [comment]
Thank you for your report. Does htmx or pjax have an init function on page load? You could try to call `ias.unbind()` and `ias.bind()` from there to reinitialize?

**Comment by JeansouLiu** [comment]
I have solved it already. Still thanks for your reply.

**Comment by fieg** [comment]
Glad to hear you solved it. Could you please share how you solved it, so others and myself can learn from it?
