### ISSUE TITLE
Accessibility and Keyboard Navigation

### ISSUE THREAD

**Issue by anybodesign** [webcreate/infinite-ajax-scroll#657]
**Description**  
Users could be able to navigate with their keyboard.

**Example**  
On a blog page with the "load more posts" button, the right behaviour when focusing on the button would be to move the focus on the new loaded post instead of remaining on the button…

All I can do now is to target the last visible post before the new ones are loaded and move the focus to it :

```
ias.on('append', function() {
  let lastpost = document.querySelector('.post-block:last-of-type .read-more');
  
  lastpost.focus();
}); 
```

**Comment by fieg** [comment]
Thanks for sending your feature request. 
In my [button example](https://infiniteajaxscroll.com/examples/button/) the keyboard navigation seems to keep working after loading the next page, so I'm not exactly sure how your use case is different. Can you clarify it a bit more?

**Comment by anybodesign** [comment]
Hi Jeroen 

Yes keyboard navigation works :)
But when a keyboard user hit the « load more » button, the next element he wants to reach is the new loaded post. He does not want to remain on the load button !
So you have to move the focus on the new elements has soon as the new elements are loaded. I don’t know if it’s possible 

Thomas

**Comment by fieg** [comment]
Should be possible by hooking into the [`appended`](https://docs.infiniteajaxscroll.com/reference/events#appended) event:

```
ias.on('appended', function(items) {
  let firstPostOfNewPage = items[0];
  
  firstPostOfNewPage.focus();
}); 
```

Let me know if this helps.

**Comment by anybodesign** [comment]
Hello
Sorry it doesn't work, it makes the "load more" button to disappear
and the focus remain where the button was :/

**Comment by fieg** [comment]
Sorry, I made a small error, the snippet should be:

```
ias.on('appended', function(event) {
  let first = event.items[0];
  
  first.focus();
}); 
```

Alternatively you could try to unfocus the load-more button:

```
```
ias.on('appended', function(event) {
  let btn = document.getElementById('my-load-more-button');
  
  btn.blur();
}); 
```

Let me know if this helps.

**Comment by anybodesign** [comment]
Thanks again :) but it doesn't work either
I made a screen recording to show you the result

https://nextcloud.anybodesign.com/index.php/s/XPKwQJ98BQeQtoR <https://nextcloud.anybodesign.com/index.php/s/XPKwQJ98BQeQtoR>

first part of the video with this snippet : after pressing the button, the focus doesn't move to the new post but continue to social icons below

second part with my snippet : the focus return to the last loaded item so the next keyboard tab moves to the new loaded post

It would be great if the focus could move to the first newly loaded post :)

**Comment by fieg** [comment]
Thank you for the recording, very helpful!

I still think we have to look into the `appended` event, as it's triggered after the new items are added to the page. Perhaps it only works if we focus on a link element. Could you give this a try?

```
ias.on('appended', function(event) {
  let first = event.items[0];

  first.querySelector('a').focus();
}); 
```

If this doesn't work, would it be possible to share a live url, so I can investigate further?

**Comment by anybodesign** [comment]
Hello!

Great! It works like a charm :)
This is exactly what's need to be done to improve accessibility, it could be added by default to the plugin :)

Thanks a lot!

**Comment by fieg** [comment]
Glad to hear this works! I also checked out the vid and it looks great.

I'll consider this for adding as default behavior.
