### ISSUE TITLE
Running over CDN vs npm, and pagination question

### ISSUE THREAD

**Issue by Swallowtail23** [webcreate/infinite-ajax-scroll#739]
**Support question**

**Environment**
Apache 2.4 on RHEL8

- Infinite Ajax Scroll version:
3.0.0

- Browser version:
Microsoft Edge Version 97.0.1072.69

- Operating System:
Windows 11

I've been using this great library for over 7 years, so firstly - thank you for the great work. I'm in the process of upgrading my old config to v3, and there are a couple of things I can't work out. 

**First question**
I tried installing npm and running
`npm install --save @webcreate/infinite-ajax-scroll`, but when I try and run the page I get:
Uncaught SyntaxError: Cannot use import statement outside a module

Using CDN it works fine, but I'd rather use locally - what am I missing? I don't have any other npm packages in my site.

**Second question**
Setting up pagination so 'back' works. At the moment, if I click on a result it goes to a details page for the item. Clicking back comes back to the TOP of the IAS page, not paged down to where it went from. 

I've never had this working properly, and I think I'm just not doing it correctly.
This is my new IAS config (working with CDN!):
```
            <script src="https://unpkg.com/@webcreate/infinite-ajax-scroll@3/dist/infinite-ajax-scroll.min.js"></script>
            <script type="text/javascript">
                $(document).ready(function () {
                    $(".top").hide();
                    let ias = new InfiniteAjaxScroll('.wrap', {
                        item: '.item',
                        next: '.next',
                        pagination: '.pagination', // page navigation
                        negativeMargin: 250,
                        spinner: {
                            element: '.spinner',
                            delay: 600,
                            show: function(element) {
                                element.style.opacity = '1'; // default behaviour
                            },
                            hide: function(element) {
                                element.style.opacity = '0'; // default behaviour
                            }
                        }
                    });
                    
                    ias.on('page', (event) => {
                        $(".top").show(200);
                    });

                    ias.on('last', function() {
                        let el = document.querySelector('.ias-no-more');
                        el.style.opacity = '1';
                    });
                })
            </script>
```
...and an extract of the html/php:

```<div id="resultsgrid" class='wrap'>
      <div class='gridbox gridboxbulk item'> ITEMS IN HERE </div>
      <div class="ias-no-more"> NO MORE RESULTS </div>
      <div class="spinner"><img src='/images/ajax-loader.gif' alt="LOADING"></div>
      <?php
              if (isset($next)):
                      $getString = getStringParameters($_GET, 'page');
                      ?>
                      <div class="pagination"> <?php echo "<a href='index.php{$getString}&amp;page=$next' class='next'>Next</a>"; ?></div>
              <?php endif
      ?>
</div>
```

- I know the number of results, and therefore the number of pages (number of results / 30 items per load)
- Direct linking to a results page with "&page=4" (or 5, 6, etc.) comes in at the right point, but I cannot scroll UP to earlier results
- $next is set on a rendered page with a value of 2
- An example of $getstring is:
`/index.php?adv=yes&layout=grid&name=&searchname=yes&legal=any&colourOp=AND&set%5B%5D=neo&sortBy=setdown`

How do I:
1. get IAS to provide the number of the page of results it is on to use when coming back to the page; and
2. come to a specific page (part of the results) and be able to scroll UP and down?

**Comment by fieg** [comment]
Thank you for using IAS this long! Let me try to answer your questions.

1. npm vs cdn: if you want to use it with npm, you also need to transpile the code using webpack, for example. Or you could take the already transpiled/minified code from the dist folder (that's the equivalent of using the code on CDN).
2. history support: you would need a small snippet to add the current page to the browser's url in order for this to work:

    ```js
    // update title and url then scrolling through pages
    ias.on('page', (e) => {
      document.title = e.title;
      let state = history.state;
      history.replaceState(state, e.title, e.url);
    });
    ```
3. scrolling up when coming back: sadly this is something I haven't solved yet in v3. v2 did this by presenting a link which you could click to load the previous page.

**Comment by Swallowtail23** [comment]
Thanks Jeroen, I've implemented 2. Only problem is that because of 3. it drops you back where you were (great) but you can't scroll back up (not so great lol). I'll have to have a think about which is the lesser UX issue :)

On 1, I'll test that out later... Any issues just using it from CDN? Any availability downtime?

On 3. I could probably present a button/link with previous page in a javascript div. Hmmm... will have a think. Even a "go to top" could work...

**Comment by Swallowtail23** [comment]
I've added a quick and dirty javascript that looks at the URL when the page is loaded, and if "page > 1" it loads my "go to top" button, so that addresses 3. 
For 2, I have copied the dist script to local, and it works - so all good there.

I'll close this - thanks Jeroen.
